/gate/world/daughters/name encapsulatingBox
/gate/world/daughters/insert box
/gate/encapsulatingBox/geometry/setXLength 100 mm
/gate/encapsulatingBox/geometry/setYLength 100 mm
/gate/encapsulatingBox/geometry/setZLength 100 mm
/gate/encapsulatingBox/placement/setTranslation  0 0 100 mm
/gate/encapsulatingBox/setMaterial Air
/gate/encapsulatingBox/vis/forceWireframe
/gate/encapsulatingBox/vis/setColor white
/gate/encapsulatingBox/moves/insert rotation
/gate/encapsulatingBox/rotation/setSpeed 1 deg/s
/gate/encapsulatingBox/rotation/setAxis 0 1 0

/gate/encapsulatingBox/daughters/name voxel_0001
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0001/geometry/setXLength 0.2 mm
/gate/voxel_0001/geometry/setYLength 1 mm
/gate/voxel_0001/geometry/setZLength 3.0 mm
/gate/voxel_0001/setMaterial Plastic
/gate/voxel_0001/vis/forceSolid
/gate/voxel_0001/vis/setColor yellow
/gate/voxel_0001/placement/setTranslation -15.5 0 -8.3 mm

/gate/encapsulatingBox/daughters/name voxel_0002
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0002/geometry/setXLength 0.2 mm
/gate/voxel_0002/geometry/setYLength 1 mm
/gate/voxel_0002/geometry/setZLength 1.2 mm
/gate/voxel_0002/setMaterial Plastic
/gate/voxel_0002/vis/forceSolid
/gate/voxel_0002/vis/setColor yellow
/gate/voxel_0002/placement/setTranslation -15.5 0 -5.6 mm

/gate/encapsulatingBox/daughters/name voxel_0003
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0003/geometry/setXLength 0.2 mm
/gate/voxel_0003/geometry/setYLength 1 mm
/gate/voxel_0003/geometry/setZLength 8.0 mm
/gate/voxel_0003/setMaterial Plastic
/gate/voxel_0003/vis/forceSolid
/gate/voxel_0003/vis/setColor yellow
/gate/voxel_0003/placement/setTranslation -15.3 0 -7.2 mm

/gate/encapsulatingBox/daughters/name voxel_0004
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0004/geometry/setXLength 0.2 mm
/gate/voxel_0004/geometry/setYLength 1 mm
/gate/voxel_0004/geometry/setZLength 9.0 mm
/gate/voxel_0004/setMaterial Plastic
/gate/voxel_0004/vis/forceSolid
/gate/voxel_0004/vis/setColor yellow
/gate/voxel_0004/placement/setTranslation -15.1 0 -7.1 mm

/gate/encapsulatingBox/daughters/name voxel_0005
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0005/geometry/setXLength 0.2 mm
/gate/voxel_0005/geometry/setYLength 1 mm
/gate/voxel_0005/geometry/setZLength 10.0 mm
/gate/voxel_0005/setMaterial Plastic
/gate/voxel_0005/vis/forceSolid
/gate/voxel_0005/vis/setColor yellow
/gate/voxel_0005/placement/setTranslation -14.9 0 -7.0 mm

/gate/encapsulatingBox/daughters/name voxel_0006
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0006/geometry/setXLength 0.2 mm
/gate/voxel_0006/geometry/setYLength 1 mm
/gate/voxel_0006/geometry/setZLength 11.0 mm
/gate/voxel_0006/setMaterial Plastic
/gate/voxel_0006/vis/forceSolid
/gate/voxel_0006/vis/setColor yellow
/gate/voxel_0006/placement/setTranslation -14.7 0 -6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0007
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0007/geometry/setXLength 0.2 mm
/gate/voxel_0007/geometry/setYLength 1 mm
/gate/voxel_0007/geometry/setZLength 12.2 mm
/gate/voxel_0007/setMaterial Plastic
/gate/voxel_0007/vis/forceSolid
/gate/voxel_0007/vis/setColor yellow
/gate/voxel_0007/placement/setTranslation -14.5 0 -6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0008
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0008/geometry/setXLength 0.2 mm
/gate/voxel_0008/geometry/setYLength 1 mm
/gate/voxel_0008/geometry/setZLength 13.0 mm
/gate/voxel_0008/setMaterial Plastic
/gate/voxel_0008/vis/forceSolid
/gate/voxel_0008/vis/setColor yellow
/gate/voxel_0008/placement/setTranslation -14.3 0 -6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0009
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0009/geometry/setXLength 0.2 mm
/gate/voxel_0009/geometry/setYLength 1 mm
/gate/voxel_0009/geometry/setZLength 13.8 mm
/gate/voxel_0009/setMaterial Plastic
/gate/voxel_0009/vis/forceSolid
/gate/voxel_0009/vis/setColor yellow
/gate/voxel_0009/placement/setTranslation -14.1 0 -6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0010
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0010/geometry/setXLength 0.2 mm
/gate/voxel_0010/geometry/setYLength 1 mm
/gate/voxel_0010/geometry/setZLength 14.8 mm
/gate/voxel_0010/setMaterial Plastic
/gate/voxel_0010/vis/forceSolid
/gate/voxel_0010/vis/setColor yellow
/gate/voxel_0010/placement/setTranslation -13.9 0 -6.8 mm

/gate/encapsulatingBox/daughters/name voxel_0011
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0011/geometry/setXLength 0.2 mm
/gate/voxel_0011/geometry/setYLength 1 mm
/gate/voxel_0011/geometry/setZLength 15.8 mm
/gate/voxel_0011/setMaterial Plastic
/gate/voxel_0011/vis/forceSolid
/gate/voxel_0011/vis/setColor yellow
/gate/voxel_0011/placement/setTranslation -13.7 0 -6.7 mm

/gate/encapsulatingBox/daughters/name voxel_0012
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0012/geometry/setXLength 0.2 mm
/gate/voxel_0012/geometry/setYLength 1 mm
/gate/voxel_0012/geometry/setZLength 5.0 mm
/gate/voxel_0012/setMaterial Plastic
/gate/voxel_0012/vis/forceSolid
/gate/voxel_0012/vis/setColor yellow
/gate/voxel_0012/placement/setTranslation -13.5 0 -12.5 mm

/gate/encapsulatingBox/daughters/name voxel_0013
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0013/geometry/setXLength 0.2 mm
/gate/voxel_0013/geometry/setYLength 1 mm
/gate/voxel_0013/geometry/setZLength 10.2 mm
/gate/voxel_0013/setMaterial Plastic
/gate/voxel_0013/vis/forceSolid
/gate/voxel_0013/vis/setColor yellow
/gate/voxel_0013/placement/setTranslation -13.5 0 -3.5 mm

/gate/encapsulatingBox/daughters/name voxel_0014
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0014/geometry/setXLength 0.2 mm
/gate/voxel_0014/geometry/setYLength 1 mm
/gate/voxel_0014/geometry/setZLength 4.8 mm
/gate/voxel_0014/setMaterial Plastic
/gate/voxel_0014/vis/forceSolid
/gate/voxel_0014/vis/setColor yellow
/gate/voxel_0014/placement/setTranslation -13.3 0 -12.8 mm

/gate/encapsulatingBox/daughters/name voxel_0015
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0015/geometry/setXLength 0.2 mm
/gate/voxel_0015/geometry/setYLength 1 mm
/gate/voxel_0015/geometry/setZLength 2.4 mm
/gate/voxel_0015/setMaterial Plastic
/gate/voxel_0015/vis/forceSolid
/gate/voxel_0015/vis/setColor yellow
/gate/voxel_0015/placement/setTranslation -13.3 0 -6.4 mm

/gate/encapsulatingBox/daughters/name voxel_0016
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0016/geometry/setXLength 0.2 mm
/gate/voxel_0016/geometry/setYLength 1 mm
/gate/voxel_0016/geometry/setZLength 5.0 mm
/gate/voxel_0016/setMaterial Plastic
/gate/voxel_0016/vis/forceSolid
/gate/voxel_0016/vis/setColor yellow
/gate/voxel_0016/placement/setTranslation -13.3 0 -0.5 mm

/gate/encapsulatingBox/daughters/name voxel_0017
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0017/geometry/setXLength 0.2 mm
/gate/voxel_0017/geometry/setYLength 1 mm
/gate/voxel_0017/geometry/setZLength 5.0 mm
/gate/voxel_0017/setMaterial Plastic
/gate/voxel_0017/vis/forceSolid
/gate/voxel_0017/vis/setColor yellow
/gate/voxel_0017/placement/setTranslation -13.1 0 -12.9 mm

/gate/encapsulatingBox/daughters/name voxel_0018
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0018/geometry/setXLength 0.2 mm
/gate/voxel_0018/geometry/setYLength 1 mm
/gate/voxel_0018/geometry/setZLength 2.0 mm
/gate/voxel_0018/setMaterial Plastic
/gate/voxel_0018/vis/forceSolid
/gate/voxel_0018/vis/setColor yellow
/gate/voxel_0018/placement/setTranslation -13.1 0 -6.4 mm

/gate/encapsulatingBox/daughters/name voxel_0019
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0019/geometry/setXLength 0.2 mm
/gate/voxel_0019/geometry/setYLength 1 mm
/gate/voxel_0019/geometry/setZLength 5.2 mm
/gate/voxel_0019/setMaterial Plastic
/gate/voxel_0019/vis/forceSolid
/gate/voxel_0019/vis/setColor yellow
/gate/voxel_0019/placement/setTranslation -13.1 0 -0.2 mm

/gate/encapsulatingBox/daughters/name voxel_0020
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0020/geometry/setXLength 0.2 mm
/gate/voxel_0020/geometry/setYLength 1 mm
/gate/voxel_0020/geometry/setZLength 5.4 mm
/gate/voxel_0020/setMaterial Plastic
/gate/voxel_0020/vis/forceSolid
/gate/voxel_0020/vis/setColor yellow
/gate/voxel_0020/placement/setTranslation -12.9 0 -13.1 mm

/gate/encapsulatingBox/daughters/name voxel_0021
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0021/geometry/setXLength 0.6 mm
/gate/voxel_0021/geometry/setYLength 1 mm
/gate/voxel_0021/geometry/setZLength 1.8 mm
/gate/voxel_0021/setMaterial Plastic
/gate/voxel_0021/vis/forceSolid
/gate/voxel_0021/vis/setColor yellow
/gate/voxel_0021/placement/setTranslation -12.7 0 -6.3 mm

/gate/encapsulatingBox/daughters/name voxel_0022
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0022/geometry/setXLength 0.2 mm
/gate/voxel_0022/geometry/setYLength 1 mm
/gate/voxel_0022/geometry/setZLength 5.4 mm
/gate/voxel_0022/setMaterial Plastic
/gate/voxel_0022/vis/forceSolid
/gate/voxel_0022/vis/setColor yellow
/gate/voxel_0022/placement/setTranslation -12.9 0 0.1 mm

/gate/encapsulatingBox/daughters/name voxel_0023
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0023/geometry/setXLength 0.2 mm
/gate/voxel_0023/geometry/setYLength 1 mm
/gate/voxel_0023/geometry/setZLength 5.8 mm
/gate/voxel_0023/setMaterial Plastic
/gate/voxel_0023/vis/forceSolid
/gate/voxel_0023/vis/setColor yellow
/gate/voxel_0023/placement/setTranslation -12.7 0 -13.3 mm

/gate/encapsulatingBox/daughters/name voxel_0024
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0024/geometry/setXLength 0.2 mm
/gate/voxel_0024/geometry/setYLength 1 mm
/gate/voxel_0024/geometry/setZLength 5.6 mm
/gate/voxel_0024/setMaterial Plastic
/gate/voxel_0024/vis/forceSolid
/gate/voxel_0024/vis/setColor yellow
/gate/voxel_0024/placement/setTranslation -12.7 0 0.2 mm

/gate/encapsulatingBox/daughters/name voxel_0025
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0025/geometry/setXLength 0.2 mm
/gate/voxel_0025/geometry/setYLength 1 mm
/gate/voxel_0025/geometry/setZLength 6.0 mm
/gate/voxel_0025/setMaterial Plastic
/gate/voxel_0025/vis/forceSolid
/gate/voxel_0025/vis/setColor yellow
/gate/voxel_0025/placement/setTranslation -12.5 0 -13.4 mm

/gate/encapsulatingBox/daughters/name voxel_0026
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0026/geometry/setXLength 0.2 mm
/gate/voxel_0026/geometry/setYLength 1 mm
/gate/voxel_0026/geometry/setZLength 5.6 mm
/gate/voxel_0026/setMaterial Plastic
/gate/voxel_0026/vis/forceSolid
/gate/voxel_0026/vis/setColor yellow
/gate/voxel_0026/placement/setTranslation -12.5 0 0.4 mm

/gate/encapsulatingBox/daughters/name voxel_0027
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0027/geometry/setXLength 0.2 mm
/gate/voxel_0027/geometry/setYLength 1 mm
/gate/voxel_0027/geometry/setZLength 3.0 mm
/gate/voxel_0027/setMaterial Plastic
/gate/voxel_0027/vis/forceSolid
/gate/voxel_0027/vis/setColor yellow
/gate/voxel_0027/placement/setTranslation -12.3 0 -15.1 mm

/gate/encapsulatingBox/daughters/name voxel_0028
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0028/geometry/setXLength 0.4 mm
/gate/voxel_0028/geometry/setYLength 1 mm
/gate/voxel_0028/geometry/setZLength 1.8 mm
/gate/voxel_0028/setMaterial Plastic
/gate/voxel_0028/vis/forceSolid
/gate/voxel_0028/vis/setColor yellow
/gate/voxel_0028/placement/setTranslation -12.2 0 -11.3 mm

/gate/encapsulatingBox/daughters/name voxel_0029
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0029/geometry/setXLength 0.6 mm
/gate/voxel_0029/geometry/setYLength 1 mm
/gate/voxel_0029/geometry/setZLength 1.6 mm
/gate/voxel_0029/setMaterial Plastic
/gate/voxel_0029/vis/forceSolid
/gate/voxel_0029/vis/setColor yellow
/gate/voxel_0029/placement/setTranslation -12.1 0 -6.2 mm

/gate/encapsulatingBox/daughters/name voxel_0030
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0030/geometry/setXLength 0.2 mm
/gate/voxel_0030/geometry/setYLength 1 mm
/gate/voxel_0030/geometry/setZLength 5.8 mm
/gate/voxel_0030/setMaterial Plastic
/gate/voxel_0030/vis/forceSolid
/gate/voxel_0030/vis/setColor yellow
/gate/voxel_0030/placement/setTranslation -12.3 0 0.5 mm

/gate/encapsulatingBox/daughters/name voxel_0031
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0031/geometry/setXLength 0.2 mm
/gate/voxel_0031/geometry/setYLength 1 mm
/gate/voxel_0031/geometry/setZLength 2.6 mm
/gate/voxel_0031/setMaterial Plastic
/gate/voxel_0031/vis/forceSolid
/gate/voxel_0031/vis/setColor yellow
/gate/voxel_0031/placement/setTranslation -12.1 0 -15.5 mm

/gate/encapsulatingBox/daughters/name voxel_0032
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0032/geometry/setXLength 0.2 mm
/gate/voxel_0032/geometry/setYLength 1 mm
/gate/voxel_0032/geometry/setZLength 6.2 mm
/gate/voxel_0032/setMaterial Plastic
/gate/voxel_0032/vis/forceSolid
/gate/voxel_0032/vis/setColor yellow
/gate/voxel_0032/placement/setTranslation -12.1 0 0.7 mm

/gate/encapsulatingBox/daughters/name voxel_0033
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0033/geometry/setXLength 0.2 mm
/gate/voxel_0033/geometry/setYLength 1 mm
/gate/voxel_0033/geometry/setZLength 2.6 mm
/gate/voxel_0033/setMaterial Plastic
/gate/voxel_0033/vis/forceSolid
/gate/voxel_0033/vis/setColor yellow
/gate/voxel_0033/placement/setTranslation -11.9 0 -15.7 mm

/gate/encapsulatingBox/daughters/name voxel_0034
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0034/geometry/setXLength 0.2 mm
/gate/voxel_0034/geometry/setYLength 1 mm
/gate/voxel_0034/geometry/setZLength 1.6 mm
/gate/voxel_0034/setMaterial Plastic
/gate/voxel_0034/vis/forceSolid
/gate/voxel_0034/vis/setColor yellow
/gate/voxel_0034/placement/setTranslation -11.9 0 -11.2 mm

/gate/encapsulatingBox/daughters/name voxel_0035
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0035/geometry/setXLength 0.2 mm
/gate/voxel_0035/geometry/setYLength 1 mm
/gate/voxel_0035/geometry/setZLength 6.6 mm
/gate/voxel_0035/setMaterial Plastic
/gate/voxel_0035/vis/forceSolid
/gate/voxel_0035/vis/setColor yellow
/gate/voxel_0035/placement/setTranslation -11.9 0 0.9 mm

/gate/encapsulatingBox/daughters/name voxel_0036
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0036/geometry/setXLength 0.2 mm
/gate/voxel_0036/geometry/setYLength 1 mm
/gate/voxel_0036/geometry/setZLength 2.8 mm
/gate/voxel_0036/setMaterial Plastic
/gate/voxel_0036/vis/forceSolid
/gate/voxel_0036/vis/setColor yellow
/gate/voxel_0036/placement/setTranslation -11.7 0 -16.0 mm

/gate/encapsulatingBox/daughters/name voxel_0037
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0037/geometry/setXLength 0.2 mm
/gate/voxel_0037/geometry/setYLength 1 mm
/gate/voxel_0037/geometry/setZLength 1.8 mm
/gate/voxel_0037/setMaterial Plastic
/gate/voxel_0037/vis/forceSolid
/gate/voxel_0037/vis/setColor yellow
/gate/voxel_0037/placement/setTranslation -11.7 0 -11.1 mm

/gate/encapsulatingBox/daughters/name voxel_0038
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0038/geometry/setXLength 0.6 mm
/gate/voxel_0038/geometry/setYLength 1 mm
/gate/voxel_0038/geometry/setZLength 1.4 mm
/gate/voxel_0038/setMaterial Plastic
/gate/voxel_0038/vis/forceSolid
/gate/voxel_0038/vis/setColor yellow
/gate/voxel_0038/placement/setTranslation -11.5 0 -6.1 mm

/gate/encapsulatingBox/daughters/name voxel_0039
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0039/geometry/setXLength 0.2 mm
/gate/voxel_0039/geometry/setYLength 1 mm
/gate/voxel_0039/geometry/setZLength 2.2 mm
/gate/voxel_0039/setMaterial Plastic
/gate/voxel_0039/vis/forceSolid
/gate/voxel_0039/vis/setColor yellow
/gate/voxel_0039/placement/setTranslation -11.7 0 -1.1 mm

/gate/encapsulatingBox/daughters/name voxel_0040
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0040/geometry/setXLength 0.2 mm
/gate/voxel_0040/geometry/setYLength 1 mm
/gate/voxel_0040/geometry/setZLength 3.2 mm
/gate/voxel_0040/setMaterial Plastic
/gate/voxel_0040/vis/forceSolid
/gate/voxel_0040/vis/setColor yellow
/gate/voxel_0040/placement/setTranslation -11.7 0 3.0 mm

/gate/encapsulatingBox/daughters/name voxel_0041
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0041/geometry/setXLength 0.2 mm
/gate/voxel_0041/geometry/setYLength 1 mm
/gate/voxel_0041/geometry/setZLength 3.0 mm
/gate/voxel_0041/setMaterial Plastic
/gate/voxel_0041/vis/forceSolid
/gate/voxel_0041/vis/setColor yellow
/gate/voxel_0041/placement/setTranslation -11.5 0 -16.1 mm

/gate/encapsulatingBox/daughters/name voxel_0042
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0042/geometry/setXLength 0.2 mm
/gate/voxel_0042/geometry/setYLength 1 mm
/gate/voxel_0042/geometry/setZLength 1.6 mm
/gate/voxel_0042/setMaterial Plastic
/gate/voxel_0042/vis/forceSolid
/gate/voxel_0042/vis/setColor yellow
/gate/voxel_0042/placement/setTranslation -11.5 0 -11.0 mm

/gate/encapsulatingBox/daughters/name voxel_0043
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0043/geometry/setXLength 0.8 mm
/gate/voxel_0043/geometry/setYLength 1 mm
/gate/voxel_0043/geometry/setZLength 2.0 mm
/gate/voxel_0043/setMaterial Plastic
/gate/voxel_0043/vis/forceSolid
/gate/voxel_0043/vis/setColor yellow
/gate/voxel_0043/placement/setTranslation -11.2 0 -1.2 mm

/gate/encapsulatingBox/daughters/name voxel_0044
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0044/geometry/setXLength 0.2 mm
/gate/voxel_0044/geometry/setYLength 1 mm
/gate/voxel_0044/geometry/setZLength 3.0 mm
/gate/voxel_0044/setMaterial Plastic
/gate/voxel_0044/vis/forceSolid
/gate/voxel_0044/vis/setColor yellow
/gate/voxel_0044/placement/setTranslation -11.5 0 3.3 mm

/gate/encapsulatingBox/daughters/name voxel_0045
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0045/geometry/setXLength 0.2 mm
/gate/voxel_0045/geometry/setYLength 1 mm
/gate/voxel_0045/geometry/setZLength 3.4 mm
/gate/voxel_0045/setMaterial Plastic
/gate/voxel_0045/vis/forceSolid
/gate/voxel_0045/vis/setColor yellow
/gate/voxel_0045/placement/setTranslation -11.3 0 -16.3 mm

/gate/encapsulatingBox/daughters/name voxel_0046
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0046/geometry/setXLength 0.6 mm
/gate/voxel_0046/geometry/setYLength 1 mm
/gate/voxel_0046/geometry/setZLength 1.8 mm
/gate/voxel_0046/setMaterial Plastic
/gate/voxel_0046/vis/forceSolid
/gate/voxel_0046/vis/setColor yellow
/gate/voxel_0046/placement/setTranslation -11.1 0 -10.9 mm

/gate/encapsulatingBox/daughters/name voxel_0047
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0047/geometry/setXLength 0.2 mm
/gate/voxel_0047/geometry/setYLength 1 mm
/gate/voxel_0047/geometry/setZLength 2.8 mm
/gate/voxel_0047/setMaterial Plastic
/gate/voxel_0047/vis/forceSolid
/gate/voxel_0047/vis/setColor yellow
/gate/voxel_0047/placement/setTranslation -11.3 0 3.6 mm

/gate/encapsulatingBox/daughters/name voxel_0048
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0048/geometry/setXLength 0.2 mm
/gate/voxel_0048/geometry/setYLength 1 mm
/gate/voxel_0048/geometry/setZLength 3.6 mm
/gate/voxel_0048/setMaterial Plastic
/gate/voxel_0048/vis/forceSolid
/gate/voxel_0048/vis/setColor yellow
/gate/voxel_0048/placement/setTranslation -11.1 0 -16.4 mm

/gate/encapsulatingBox/daughters/name voxel_0049
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0049/geometry/setXLength 0.6 mm
/gate/voxel_0049/geometry/setYLength 1 mm
/gate/voxel_0049/geometry/setZLength 1.2 mm
/gate/voxel_0049/setMaterial Plastic
/gate/voxel_0049/vis/forceSolid
/gate/voxel_0049/vis/setColor yellow
/gate/voxel_0049/placement/setTranslation -10.9 0 -6.0 mm

/gate/encapsulatingBox/daughters/name voxel_0050
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0050/geometry/setXLength 0.2 mm
/gate/voxel_0050/geometry/setYLength 1 mm
/gate/voxel_0050/geometry/setZLength 2.6 mm
/gate/voxel_0050/setMaterial Plastic
/gate/voxel_0050/vis/forceSolid
/gate/voxel_0050/vis/setColor yellow
/gate/voxel_0050/placement/setTranslation -11.1 0 3.9 mm

/gate/encapsulatingBox/daughters/name voxel_0051
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0051/geometry/setXLength 0.4 mm
/gate/voxel_0051/geometry/setYLength 1 mm
/gate/voxel_0051/geometry/setZLength 3.8 mm
/gate/voxel_0051/setMaterial Plastic
/gate/voxel_0051/vis/forceSolid
/gate/voxel_0051/vis/setColor yellow
/gate/voxel_0051/placement/setTranslation -10.8 0 -16.5 mm

/gate/encapsulatingBox/daughters/name voxel_0052
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0052/geometry/setXLength 0.2 mm
/gate/voxel_0052/geometry/setYLength 1 mm
/gate/voxel_0052/geometry/setZLength 2.6 mm
/gate/voxel_0052/setMaterial Plastic
/gate/voxel_0052/vis/forceSolid
/gate/voxel_0052/vis/setColor yellow
/gate/voxel_0052/placement/setTranslation -10.9 0 4.3 mm

/gate/encapsulatingBox/daughters/name voxel_0053
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0053/geometry/setXLength 0.4 mm
/gate/voxel_0053/geometry/setYLength 1 mm
/gate/voxel_0053/geometry/setZLength 1.6 mm
/gate/voxel_0053/setMaterial Plastic
/gate/voxel_0053/vis/forceSolid
/gate/voxel_0053/vis/setColor yellow
/gate/voxel_0053/placement/setTranslation -10.6 0 -10.8 mm

/gate/encapsulatingBox/daughters/name voxel_0054
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0054/geometry/setXLength 1.0 mm
/gate/voxel_0054/geometry/setYLength 1 mm
/gate/voxel_0054/geometry/setZLength 1.8 mm
/gate/voxel_0054/setMaterial Plastic
/gate/voxel_0054/vis/forceSolid
/gate/voxel_0054/vis/setColor yellow
/gate/voxel_0054/placement/setTranslation -10.3 0 -1.1 mm

/gate/encapsulatingBox/daughters/name voxel_0055
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0055/geometry/setXLength 0.2 mm
/gate/voxel_0055/geometry/setYLength 1 mm
/gate/voxel_0055/geometry/setZLength 2.8 mm
/gate/voxel_0055/setMaterial Plastic
/gate/voxel_0055/vis/forceSolid
/gate/voxel_0055/vis/setColor yellow
/gate/voxel_0055/placement/setTranslation -10.7 0 4.6 mm

/gate/encapsulatingBox/daughters/name voxel_0056
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0056/geometry/setXLength 0.2 mm
/gate/voxel_0056/geometry/setYLength 1 mm
/gate/voxel_0056/geometry/setZLength 4.0 mm
/gate/voxel_0056/setMaterial Plastic
/gate/voxel_0056/vis/forceSolid
/gate/voxel_0056/vis/setColor yellow
/gate/voxel_0056/placement/setTranslation -10.5 0 -16.6 mm

/gate/encapsulatingBox/daughters/name voxel_0057
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0057/geometry/setXLength 0.8 mm
/gate/voxel_0057/geometry/setYLength 1 mm
/gate/voxel_0057/geometry/setZLength 1.4 mm
/gate/voxel_0057/setMaterial Plastic
/gate/voxel_0057/vis/forceSolid
/gate/voxel_0057/vis/setColor yellow
/gate/voxel_0057/placement/setTranslation -10.2 0 -5.9 mm

/gate/encapsulatingBox/daughters/name voxel_0058
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0058/geometry/setXLength 0.2 mm
/gate/voxel_0058/geometry/setYLength 1 mm
/gate/voxel_0058/geometry/setZLength 2.6 mm
/gate/voxel_0058/setMaterial Plastic
/gate/voxel_0058/vis/forceSolid
/gate/voxel_0058/vis/setColor yellow
/gate/voxel_0058/placement/setTranslation -10.5 0 4.9 mm

/gate/encapsulatingBox/daughters/name voxel_0059
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0059/geometry/setXLength 0.4 mm
/gate/voxel_0059/geometry/setYLength 1 mm
/gate/voxel_0059/geometry/setZLength 4.2 mm
/gate/voxel_0059/setMaterial Plastic
/gate/voxel_0059/vis/forceSolid
/gate/voxel_0059/vis/setColor yellow
/gate/voxel_0059/placement/setTranslation -10.2 0 -16.7 mm

/gate/encapsulatingBox/daughters/name voxel_0060
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0060/geometry/setXLength 0.2 mm
/gate/voxel_0060/geometry/setYLength 1 mm
/gate/voxel_0060/geometry/setZLength 1.4 mm
/gate/voxel_0060/setMaterial Plastic
/gate/voxel_0060/vis/forceSolid
/gate/voxel_0060/vis/setColor yellow
/gate/voxel_0060/placement/setTranslation -10.3 0 -10.9 mm

/gate/encapsulatingBox/daughters/name voxel_0061
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0061/geometry/setXLength 0.2 mm
/gate/voxel_0061/geometry/setYLength 1 mm
/gate/voxel_0061/geometry/setZLength 2.6 mm
/gate/voxel_0061/setMaterial Plastic
/gate/voxel_0061/vis/forceSolid
/gate/voxel_0061/vis/setColor yellow
/gate/voxel_0061/placement/setTranslation -10.3 0 5.1 mm

/gate/encapsulatingBox/daughters/name voxel_0062
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0062/geometry/setXLength 0.2 mm
/gate/voxel_0062/geometry/setYLength 1 mm
/gate/voxel_0062/geometry/setZLength 1.2 mm
/gate/voxel_0062/setMaterial Plastic
/gate/voxel_0062/vis/forceSolid
/gate/voxel_0062/vis/setColor yellow
/gate/voxel_0062/placement/setTranslation -10.1 0 -10.8 mm

/gate/encapsulatingBox/daughters/name voxel_0063
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0063/geometry/setXLength 0.2 mm
/gate/voxel_0063/geometry/setYLength 1 mm
/gate/voxel_0063/geometry/setZLength 2.8 mm
/gate/voxel_0063/setMaterial Plastic
/gate/voxel_0063/vis/forceSolid
/gate/voxel_0063/vis/setColor yellow
/gate/voxel_0063/placement/setTranslation -10.1 0 5.4 mm

/gate/encapsulatingBox/daughters/name voxel_0064
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0064/geometry/setXLength 0.2 mm
/gate/voxel_0064/geometry/setYLength 1 mm
/gate/voxel_0064/geometry/setZLength 4.4 mm
/gate/voxel_0064/setMaterial Plastic
/gate/voxel_0064/vis/forceSolid
/gate/voxel_0064/vis/setColor yellow
/gate/voxel_0064/placement/setTranslation -9.9 0 -16.8 mm

/gate/encapsulatingBox/daughters/name voxel_0065
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0065/geometry/setXLength 0.2 mm
/gate/voxel_0065/geometry/setYLength 1 mm
/gate/voxel_0065/geometry/setZLength 1.4 mm
/gate/voxel_0065/setMaterial Plastic
/gate/voxel_0065/vis/forceSolid
/gate/voxel_0065/vis/setColor yellow
/gate/voxel_0065/placement/setTranslation -9.9 0 -10.7 mm

/gate/encapsulatingBox/daughters/name voxel_0066
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0066/geometry/setXLength 0.2 mm
/gate/voxel_0066/geometry/setYLength 1 mm
/gate/voxel_0066/geometry/setZLength 3.2 mm
/gate/voxel_0066/setMaterial Plastic
/gate/voxel_0066/vis/forceSolid
/gate/voxel_0066/vis/setColor yellow
/gate/voxel_0066/placement/setTranslation -9.9 0 5.8 mm

/gate/encapsulatingBox/daughters/name voxel_0067
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0067/geometry/setXLength 0.2 mm
/gate/voxel_0067/geometry/setYLength 1 mm
/gate/voxel_0067/geometry/setZLength 4.8 mm
/gate/voxel_0067/setMaterial Plastic
/gate/voxel_0067/vis/forceSolid
/gate/voxel_0067/vis/setColor yellow
/gate/voxel_0067/placement/setTranslation -9.7 0 -16.8 mm

/gate/encapsulatingBox/daughters/name voxel_0068
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0068/geometry/setXLength 1.0 mm
/gate/voxel_0068/geometry/setYLength 1 mm
/gate/voxel_0068/geometry/setZLength 1.2 mm
/gate/voxel_0068/setMaterial Plastic
/gate/voxel_0068/vis/forceSolid
/gate/voxel_0068/vis/setColor yellow
/gate/voxel_0068/placement/setTranslation -9.3 0 -10.6 mm

/gate/encapsulatingBox/daughters/name voxel_0069
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0069/geometry/setXLength 1.2 mm
/gate/voxel_0069/geometry/setYLength 1 mm
/gate/voxel_0069/geometry/setZLength 1.6 mm
/gate/voxel_0069/setMaterial Plastic
/gate/voxel_0069/vis/forceSolid
/gate/voxel_0069/vis/setColor yellow
/gate/voxel_0069/placement/setTranslation -9.2 0 -5.8 mm

/gate/encapsulatingBox/daughters/name voxel_0070
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0070/geometry/setXLength 0.6 mm
/gate/voxel_0070/geometry/setYLength 1 mm
/gate/voxel_0070/geometry/setZLength 1.6 mm
/gate/voxel_0070/setMaterial Plastic
/gate/voxel_0070/vis/forceSolid
/gate/voxel_0070/vis/setColor yellow
/gate/voxel_0070/placement/setTranslation -9.5 0 -1.0 mm

/gate/encapsulatingBox/daughters/name voxel_0071
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0071/geometry/setXLength 0.2 mm
/gate/voxel_0071/geometry/setYLength 1 mm
/gate/voxel_0071/geometry/setZLength 3.2 mm
/gate/voxel_0071/setMaterial Plastic
/gate/voxel_0071/vis/forceSolid
/gate/voxel_0071/vis/setColor yellow
/gate/voxel_0071/placement/setTranslation -9.7 0 6.0 mm

/gate/encapsulatingBox/daughters/name voxel_0072
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0072/geometry/setXLength 0.4 mm
/gate/voxel_0072/geometry/setYLength 1 mm
/gate/voxel_0072/geometry/setZLength 5.0 mm
/gate/voxel_0072/setMaterial Plastic
/gate/voxel_0072/vis/forceSolid
/gate/voxel_0072/vis/setColor yellow
/gate/voxel_0072/placement/setTranslation -9.4 0 -16.9 mm

/gate/encapsulatingBox/daughters/name voxel_0073
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0073/geometry/setXLength 0.2 mm
/gate/voxel_0073/geometry/setYLength 1 mm
/gate/voxel_0073/geometry/setZLength 3.2 mm
/gate/voxel_0073/setMaterial Plastic
/gate/voxel_0073/vis/forceSolid
/gate/voxel_0073/vis/setColor yellow
/gate/voxel_0073/placement/setTranslation -9.5 0 6.2 mm

/gate/encapsulatingBox/daughters/name voxel_0074
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0074/geometry/setXLength 0.2 mm
/gate/voxel_0074/geometry/setYLength 1 mm
/gate/voxel_0074/geometry/setZLength 3.4 mm
/gate/voxel_0074/setMaterial Plastic
/gate/voxel_0074/vis/forceSolid
/gate/voxel_0074/vis/setColor yellow
/gate/voxel_0074/placement/setTranslation -9.3 0 6.5 mm

/gate/encapsulatingBox/daughters/name voxel_0075
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0075/geometry/setXLength 0.2 mm
/gate/voxel_0075/geometry/setYLength 1 mm
/gate/voxel_0075/geometry/setZLength 2.2 mm
/gate/voxel_0075/setMaterial Plastic
/gate/voxel_0075/vis/forceSolid
/gate/voxel_0075/vis/setColor yellow
/gate/voxel_0075/placement/setTranslation -9.1 0 -18.7 mm

/gate/encapsulatingBox/daughters/name voxel_0076
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0076/geometry/setXLength 0.2 mm
/gate/voxel_0076/geometry/setYLength 1 mm
/gate/voxel_0076/geometry/setZLength 2.2 mm
/gate/voxel_0076/setMaterial Plastic
/gate/voxel_0076/vis/forceSolid
/gate/voxel_0076/vis/setColor yellow
/gate/voxel_0076/placement/setTranslation -9.1 0 -15.5 mm

/gate/encapsulatingBox/daughters/name voxel_0077
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0077/geometry/setXLength 0.6 mm
/gate/voxel_0077/geometry/setYLength 1 mm
/gate/voxel_0077/geometry/setZLength 1.4 mm
/gate/voxel_0077/setMaterial Plastic
/gate/voxel_0077/vis/forceSolid
/gate/voxel_0077/vis/setColor yellow
/gate/voxel_0077/placement/setTranslation -8.9 0 -0.9 mm

/gate/encapsulatingBox/daughters/name voxel_0078
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0078/geometry/setXLength 0.2 mm
/gate/voxel_0078/geometry/setYLength 1 mm
/gate/voxel_0078/geometry/setZLength 3.6 mm
/gate/voxel_0078/setMaterial Plastic
/gate/voxel_0078/vis/forceSolid
/gate/voxel_0078/vis/setColor yellow
/gate/voxel_0078/placement/setTranslation -9.1 0 6.6 mm

/gate/encapsulatingBox/daughters/name voxel_0079
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0079/geometry/setXLength 0.2 mm
/gate/voxel_0079/geometry/setYLength 1 mm
/gate/voxel_0079/geometry/setZLength 2.2 mm
/gate/voxel_0079/setMaterial Plastic
/gate/voxel_0079/vis/forceSolid
/gate/voxel_0079/vis/setColor yellow
/gate/voxel_0079/placement/setTranslation -8.9 0 -18.9 mm

/gate/encapsulatingBox/daughters/name voxel_0080
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0080/geometry/setXLength 0.4 mm
/gate/voxel_0080/geometry/setYLength 1 mm
/gate/voxel_0080/geometry/setZLength 2.0 mm
/gate/voxel_0080/setMaterial Plastic
/gate/voxel_0080/vis/forceSolid
/gate/voxel_0080/vis/setColor yellow
/gate/voxel_0080/placement/setTranslation -8.8 0 -15.4 mm

/gate/encapsulatingBox/daughters/name voxel_0081
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0081/geometry/setXLength 0.2 mm
/gate/voxel_0081/geometry/setYLength 1 mm
/gate/voxel_0081/geometry/setZLength 3.8 mm
/gate/voxel_0081/setMaterial Plastic
/gate/voxel_0081/vis/forceSolid
/gate/voxel_0081/vis/setColor yellow
/gate/voxel_0081/placement/setTranslation -8.9 0 6.7 mm

/gate/encapsulatingBox/daughters/name voxel_0082
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0082/geometry/setXLength 0.2 mm
/gate/voxel_0082/geometry/setYLength 1 mm
/gate/voxel_0082/geometry/setZLength 2.0 mm
/gate/voxel_0082/setMaterial Plastic
/gate/voxel_0082/vis/forceSolid
/gate/voxel_0082/vis/setColor yellow
/gate/voxel_0082/placement/setTranslation -8.7 0 -19.2 mm

/gate/encapsulatingBox/daughters/name voxel_0083
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0083/geometry/setXLength 0.4 mm
/gate/voxel_0083/geometry/setYLength 1 mm
/gate/voxel_0083/geometry/setZLength 1.0 mm
/gate/voxel_0083/setMaterial Plastic
/gate/voxel_0083/vis/forceSolid
/gate/voxel_0083/vis/setColor yellow
/gate/voxel_0083/placement/setTranslation -8.6 0 -10.5 mm

/gate/encapsulatingBox/daughters/name voxel_0084
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0084/geometry/setXLength 0.2 mm
/gate/voxel_0084/geometry/setYLength 1 mm
/gate/voxel_0084/geometry/setZLength 4.2 mm
/gate/voxel_0084/setMaterial Plastic
/gate/voxel_0084/vis/forceSolid
/gate/voxel_0084/vis/setColor yellow
/gate/voxel_0084/placement/setTranslation -8.7 0 6.7 mm

/gate/encapsulatingBox/daughters/name voxel_0085
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0085/geometry/setXLength 0.2 mm
/gate/voxel_0085/geometry/setYLength 1 mm
/gate/voxel_0085/geometry/setZLength 2.0 mm
/gate/voxel_0085/setMaterial Plastic
/gate/voxel_0085/vis/forceSolid
/gate/voxel_0085/vis/setColor yellow
/gate/voxel_0085/placement/setTranslation -8.5 0 -19.4 mm

/gate/encapsulatingBox/daughters/name voxel_0086
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0086/geometry/setXLength 0.6 mm
/gate/voxel_0086/geometry/setYLength 1 mm
/gate/voxel_0086/geometry/setZLength 2.0 mm
/gate/voxel_0086/setMaterial Plastic
/gate/voxel_0086/vis/forceSolid
/gate/voxel_0086/vis/setColor yellow
/gate/voxel_0086/placement/setTranslation -8.3 0 -15.2 mm

/gate/encapsulatingBox/daughters/name voxel_0087
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0087/geometry/setXLength 0.4 mm
/gate/voxel_0087/geometry/setYLength 1 mm
/gate/voxel_0087/geometry/setZLength 1.8 mm
/gate/voxel_0087/setMaterial Plastic
/gate/voxel_0087/vis/forceSolid
/gate/voxel_0087/vis/setColor yellow
/gate/voxel_0087/placement/setTranslation -8.4 0 -5.7 mm

/gate/encapsulatingBox/daughters/name voxel_0088
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0088/geometry/setXLength 1.0 mm
/gate/voxel_0088/geometry/setYLength 1 mm
/gate/voxel_0088/geometry/setZLength 1.6 mm
/gate/voxel_0088/setMaterial Plastic
/gate/voxel_0088/vis/forceSolid
/gate/voxel_0088/vis/setColor yellow
/gate/voxel_0088/placement/setTranslation -8.1 0 -0.8 mm

/gate/encapsulatingBox/daughters/name voxel_0089
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0089/geometry/setXLength 0.2 mm
/gate/voxel_0089/geometry/setYLength 1 mm
/gate/voxel_0089/geometry/setZLength 4.4 mm
/gate/voxel_0089/setMaterial Plastic
/gate/voxel_0089/vis/forceSolid
/gate/voxel_0089/vis/setColor yellow
/gate/voxel_0089/placement/setTranslation -8.5 0 6.8 mm

/gate/encapsulatingBox/daughters/name voxel_0090
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0090/geometry/setXLength 0.4 mm
/gate/voxel_0090/geometry/setYLength 1 mm
/gate/voxel_0090/geometry/setZLength 2.0 mm
/gate/voxel_0090/setMaterial Plastic
/gate/voxel_0090/vis/forceSolid
/gate/voxel_0090/vis/setColor yellow
/gate/voxel_0090/placement/setTranslation -8.2 0 -19.6 mm

/gate/encapsulatingBox/daughters/name voxel_0091
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0091/geometry/setXLength 0.6 mm
/gate/voxel_0091/geometry/setYLength 1 mm
/gate/voxel_0091/geometry/setZLength 1.2 mm
/gate/voxel_0091/setMaterial Plastic
/gate/voxel_0091/vis/forceSolid
/gate/voxel_0091/vis/setColor yellow
/gate/voxel_0091/placement/setTranslation -8.1 0 -10.4 mm

/gate/encapsulatingBox/daughters/name voxel_0092
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0092/geometry/setXLength 0.2 mm
/gate/voxel_0092/geometry/setYLength 1 mm
/gate/voxel_0092/geometry/setZLength 4.6 mm
/gate/voxel_0092/setMaterial Plastic
/gate/voxel_0092/vis/forceSolid
/gate/voxel_0092/vis/setColor yellow
/gate/voxel_0092/placement/setTranslation -8.3 0 6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0093
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0093/geometry/setXLength 0.6 mm
/gate/voxel_0093/geometry/setYLength 1 mm
/gate/voxel_0093/geometry/setZLength 2.0 mm
/gate/voxel_0093/setMaterial Plastic
/gate/voxel_0093/vis/forceSolid
/gate/voxel_0093/vis/setColor yellow
/gate/voxel_0093/placement/setTranslation -7.9 0 -5.6 mm

/gate/encapsulatingBox/daughters/name voxel_0094
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0094/geometry/setXLength 0.2 mm
/gate/voxel_0094/geometry/setYLength 1 mm
/gate/voxel_0094/geometry/setZLength 5.0 mm
/gate/voxel_0094/setMaterial Plastic
/gate/voxel_0094/vis/forceSolid
/gate/voxel_0094/vis/setColor yellow
/gate/voxel_0094/placement/setTranslation -8.1 0 6.9 mm

/gate/encapsulatingBox/daughters/name voxel_0095
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0095/geometry/setXLength 0.4 mm
/gate/voxel_0095/geometry/setYLength 1 mm
/gate/voxel_0095/geometry/setZLength 2.0 mm
/gate/voxel_0095/setMaterial Plastic
/gate/voxel_0095/vis/forceSolid
/gate/voxel_0095/vis/setColor yellow
/gate/voxel_0095/placement/setTranslation -7.8 0 -19.8 mm

/gate/encapsulatingBox/daughters/name voxel_0096
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0096/geometry/setXLength 0.2 mm
/gate/voxel_0096/geometry/setYLength 1 mm
/gate/voxel_0096/geometry/setZLength 1.8 mm
/gate/voxel_0096/setMaterial Plastic
/gate/voxel_0096/vis/forceSolid
/gate/voxel_0096/vis/setColor yellow
/gate/voxel_0096/placement/setTranslation -7.9 0 -15.1 mm

/gate/encapsulatingBox/daughters/name voxel_0097
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0097/geometry/setXLength 0.2 mm
/gate/voxel_0097/geometry/setYLength 1 mm
/gate/voxel_0097/geometry/setZLength 2.2 mm
/gate/voxel_0097/setMaterial Plastic
/gate/voxel_0097/vis/forceSolid
/gate/voxel_0097/vis/setColor yellow
/gate/voxel_0097/placement/setTranslation -7.9 0 5.3 mm

/gate/encapsulatingBox/daughters/name voxel_0098
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0098/geometry/setXLength 0.2 mm
/gate/voxel_0098/geometry/setYLength 1 mm
/gate/voxel_0098/geometry/setZLength 2.4 mm
/gate/voxel_0098/setMaterial Plastic
/gate/voxel_0098/vis/forceSolid
/gate/voxel_0098/vis/setColor yellow
/gate/voxel_0098/placement/setTranslation -7.9 0 8.6 mm

/gate/encapsulatingBox/daughters/name voxel_0099
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0099/geometry/setXLength 0.2 mm
/gate/voxel_0099/geometry/setYLength 1 mm
/gate/voxel_0099/geometry/setZLength 0.8 mm
/gate/voxel_0099/setMaterial Plastic
/gate/voxel_0099/vis/forceSolid
/gate/voxel_0099/vis/setColor yellow
/gate/voxel_0099/placement/setTranslation -7.7 0 -15.6 mm

/gate/encapsulatingBox/daughters/name voxel_0100
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0100/geometry/setXLength 0.2 mm
/gate/voxel_0100/geometry/setYLength 1 mm
/gate/voxel_0100/geometry/setZLength 0.6 mm
/gate/voxel_0100/setMaterial Plastic
/gate/voxel_0100/vis/forceSolid
/gate/voxel_0100/vis/setColor yellow
/gate/voxel_0100/placement/setTranslation -7.7 0 -14.5 mm

/gate/encapsulatingBox/daughters/name voxel_0101
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0101/geometry/setXLength 0.4 mm
/gate/voxel_0101/geometry/setYLength 1 mm
/gate/voxel_0101/geometry/setZLength 1.4 mm
/gate/voxel_0101/setMaterial Plastic
/gate/voxel_0101/vis/forceSolid
/gate/voxel_0101/vis/setColor yellow
/gate/voxel_0101/placement/setTranslation -7.6 0 -10.3 mm

/gate/encapsulatingBox/daughters/name voxel_0102
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0102/geometry/setXLength 0.2 mm
/gate/voxel_0102/geometry/setYLength 1 mm
/gate/voxel_0102/geometry/setZLength 2.2 mm
/gate/voxel_0102/setMaterial Plastic
/gate/voxel_0102/vis/forceSolid
/gate/voxel_0102/vis/setColor yellow
/gate/voxel_0102/placement/setTranslation -7.7 0 4.9 mm

/gate/encapsulatingBox/daughters/name voxel_0103
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0103/geometry/setXLength 0.2 mm
/gate/voxel_0103/geometry/setYLength 1 mm
/gate/voxel_0103/geometry/setZLength 2.2 mm
/gate/voxel_0103/setMaterial Plastic
/gate/voxel_0103/vis/forceSolid
/gate/voxel_0103/vis/setColor yellow
/gate/voxel_0103/placement/setTranslation -7.7 0 8.9 mm

/gate/encapsulatingBox/daughters/name voxel_0104
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0104/geometry/setXLength 0.4 mm
/gate/voxel_0104/geometry/setYLength 1 mm
/gate/voxel_0104/geometry/setZLength 2.2 mm
/gate/voxel_0104/setMaterial Plastic
/gate/voxel_0104/vis/forceSolid
/gate/voxel_0104/vis/setColor yellow
/gate/voxel_0104/placement/setTranslation -7.4 0 -19.9 mm

/gate/encapsulatingBox/daughters/name voxel_0105
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0105/geometry/setXLength 0.2 mm
/gate/voxel_0105/geometry/setYLength 1 mm
/gate/voxel_0105/geometry/setZLength 0.6 mm
/gate/voxel_0105/setMaterial Plastic
/gate/voxel_0105/vis/forceSolid
/gate/voxel_0105/vis/setColor yellow
/gate/voxel_0105/placement/setTranslation -7.5 0 -15.5 mm

/gate/encapsulatingBox/daughters/name voxel_0106
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0106/geometry/setXLength 0.2 mm
/gate/voxel_0106/geometry/setYLength 1 mm
/gate/voxel_0106/geometry/setZLength 0.8 mm
/gate/voxel_0106/setMaterial Plastic
/gate/voxel_0106/vis/forceSolid
/gate/voxel_0106/vis/setColor yellow
/gate/voxel_0106/placement/setTranslation -7.5 0 -14.4 mm

/gate/encapsulatingBox/daughters/name voxel_0107
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0107/geometry/setXLength 0.4 mm
/gate/voxel_0107/geometry/setYLength 1 mm
/gate/voxel_0107/geometry/setZLength 2.2 mm
/gate/voxel_0107/setMaterial Plastic
/gate/voxel_0107/vis/forceSolid
/gate/voxel_0107/vis/setColor yellow
/gate/voxel_0107/placement/setTranslation -7.4 0 -5.5 mm

/gate/encapsulatingBox/daughters/name voxel_0108
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0108/geometry/setXLength 0.4 mm
/gate/voxel_0108/geometry/setYLength 1 mm
/gate/voxel_0108/geometry/setZLength 1.8 mm
/gate/voxel_0108/setMaterial Plastic
/gate/voxel_0108/vis/forceSolid
/gate/voxel_0108/vis/setColor yellow
/gate/voxel_0108/placement/setTranslation -7.4 0 -0.7 mm

/gate/encapsulatingBox/daughters/name voxel_0109
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0109/geometry/setXLength 0.2 mm
/gate/voxel_0109/geometry/setYLength 1 mm
/gate/voxel_0109/geometry/setZLength 2.2 mm
/gate/voxel_0109/setMaterial Plastic
/gate/voxel_0109/vis/forceSolid
/gate/voxel_0109/vis/setColor yellow
/gate/voxel_0109/placement/setTranslation -7.5 0 4.7 mm

/gate/encapsulatingBox/daughters/name voxel_0110
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0110/geometry/setXLength 0.2 mm
/gate/voxel_0110/geometry/setYLength 1 mm
/gate/voxel_0110/geometry/setZLength 2.0 mm
/gate/voxel_0110/setMaterial Plastic
/gate/voxel_0110/vis/forceSolid
/gate/voxel_0110/vis/setColor yellow
/gate/voxel_0110/placement/setTranslation -7.5 0 9.2 mm

/gate/encapsulatingBox/daughters/name voxel_0111
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0111/geometry/setXLength 0.2 mm
/gate/voxel_0111/geometry/setYLength 1 mm
/gate/voxel_0111/geometry/setZLength 1.8 mm
/gate/voxel_0111/setMaterial Plastic
/gate/voxel_0111/vis/forceSolid
/gate/voxel_0111/vis/setColor yellow
/gate/voxel_0111/placement/setTranslation -7.3 0 -14.9 mm

/gate/encapsulatingBox/daughters/name voxel_0112
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0112/geometry/setXLength 0.4 mm
/gate/voxel_0112/geometry/setYLength 1 mm
/gate/voxel_0112/geometry/setZLength 1.6 mm
/gate/voxel_0112/setMaterial Plastic
/gate/voxel_0112/vis/forceSolid
/gate/voxel_0112/vis/setColor yellow
/gate/voxel_0112/placement/setTranslation -7.2 0 -10.2 mm

/gate/encapsulatingBox/daughters/name voxel_0113
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0113/geometry/setXLength 0.2 mm
/gate/voxel_0113/geometry/setYLength 1 mm
/gate/voxel_0113/geometry/setZLength 2.4 mm
/gate/voxel_0113/setMaterial Plastic
/gate/voxel_0113/vis/forceSolid
/gate/voxel_0113/vis/setColor yellow
/gate/voxel_0113/placement/setTranslation -7.3 0 4.6 mm

/gate/encapsulatingBox/daughters/name voxel_0114
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0114/geometry/setXLength 0.2 mm
/gate/voxel_0114/geometry/setYLength 1 mm
/gate/voxel_0114/geometry/setZLength 2.0 mm
/gate/voxel_0114/setMaterial Plastic
/gate/voxel_0114/vis/forceSolid
/gate/voxel_0114/vis/setColor yellow
/gate/voxel_0114/placement/setTranslation -7.3 0 9.4 mm

/gate/encapsulatingBox/daughters/name voxel_0115
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0115/geometry/setXLength 0.4 mm
/gate/voxel_0115/geometry/setYLength 1 mm
/gate/voxel_0115/geometry/setZLength 2.2 mm
/gate/voxel_0115/setMaterial Plastic
/gate/voxel_0115/vis/forceSolid
/gate/voxel_0115/vis/setColor yellow
/gate/voxel_0115/placement/setTranslation -7.0 0 -20.1 mm

/gate/encapsulatingBox/daughters/name voxel_0116
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0116/geometry/setXLength 0.6 mm
/gate/voxel_0116/geometry/setYLength 1 mm
/gate/voxel_0116/geometry/setZLength 1.6 mm
/gate/voxel_0116/setMaterial Plastic
/gate/voxel_0116/vis/forceSolid
/gate/voxel_0116/vis/setColor yellow
/gate/voxel_0116/placement/setTranslation -6.9 0 -14.8 mm

/gate/encapsulatingBox/daughters/name voxel_0117
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0117/geometry/setXLength 0.2 mm
/gate/voxel_0117/geometry/setYLength 1 mm
/gate/voxel_0117/geometry/setZLength 2.8 mm
/gate/voxel_0117/setMaterial Plastic
/gate/voxel_0117/vis/forceSolid
/gate/voxel_0117/vis/setColor yellow
/gate/voxel_0117/placement/setTranslation -7.1 0 -5.4 mm

/gate/encapsulatingBox/daughters/name voxel_0118
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0118/geometry/setXLength 0.2 mm
/gate/voxel_0118/geometry/setYLength 1 mm
/gate/voxel_0118/geometry/setZLength 2.2 mm
/gate/voxel_0118/setMaterial Plastic
/gate/voxel_0118/vis/forceSolid
/gate/voxel_0118/vis/setColor yellow
/gate/voxel_0118/placement/setTranslation -7.1 0 -0.7 mm

/gate/encapsulatingBox/daughters/name voxel_0119
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0119/geometry/setXLength 0.2 mm
/gate/voxel_0119/geometry/setYLength 1 mm
/gate/voxel_0119/geometry/setZLength 2.4 mm
/gate/voxel_0119/setMaterial Plastic
/gate/voxel_0119/vis/forceSolid
/gate/voxel_0119/vis/setColor yellow
/gate/voxel_0119/placement/setTranslation -7.1 0 4.4 mm

/gate/encapsulatingBox/daughters/name voxel_0120
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0120/geometry/setXLength 0.2 mm
/gate/voxel_0120/geometry/setYLength 1 mm
/gate/voxel_0120/geometry/setZLength 2.0 mm
/gate/voxel_0120/setMaterial Plastic
/gate/voxel_0120/vis/forceSolid
/gate/voxel_0120/vis/setColor yellow
/gate/voxel_0120/placement/setTranslation -7.1 0 9.6 mm

/gate/encapsulatingBox/daughters/name voxel_0121
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0121/geometry/setXLength 0.2 mm
/gate/voxel_0121/geometry/setYLength 1 mm
/gate/voxel_0121/geometry/setZLength 1.8 mm
/gate/voxel_0121/setMaterial Plastic
/gate/voxel_0121/vis/forceSolid
/gate/voxel_0121/vis/setColor yellow
/gate/voxel_0121/placement/setTranslation -6.9 0 -10.1 mm

/gate/encapsulatingBox/daughters/name voxel_0122
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0122/geometry/setXLength 0.2 mm
/gate/voxel_0122/geometry/setYLength 1 mm
/gate/voxel_0122/geometry/setZLength 7.8 mm
/gate/voxel_0122/setMaterial Plastic
/gate/voxel_0122/vis/forceSolid
/gate/voxel_0122/vis/setColor yellow
/gate/voxel_0122/placement/setTranslation -6.9 0 -3.5 mm

/gate/encapsulatingBox/daughters/name voxel_0123
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0123/geometry/setXLength 0.2 mm
/gate/voxel_0123/geometry/setYLength 1 mm
/gate/voxel_0123/geometry/setZLength 2.4 mm
/gate/voxel_0123/setMaterial Plastic
/gate/voxel_0123/vis/forceSolid
/gate/voxel_0123/vis/setColor yellow
/gate/voxel_0123/placement/setTranslation -6.9 0 4.2 mm

/gate/encapsulatingBox/daughters/name voxel_0124
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0124/geometry/setXLength 0.2 mm
/gate/voxel_0124/geometry/setYLength 1 mm
/gate/voxel_0124/geometry/setZLength 1.8 mm
/gate/voxel_0124/setMaterial Plastic
/gate/voxel_0124/vis/forceSolid
/gate/voxel_0124/vis/setColor yellow
/gate/voxel_0124/placement/setTranslation -6.9 0 9.9 mm

/gate/encapsulatingBox/daughters/name voxel_0125
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0125/geometry/setXLength 0.4 mm
/gate/voxel_0125/geometry/setYLength 1 mm
/gate/voxel_0125/geometry/setZLength 2.4 mm
/gate/voxel_0125/setMaterial Plastic
/gate/voxel_0125/vis/forceSolid
/gate/voxel_0125/vis/setColor yellow
/gate/voxel_0125/placement/setTranslation -6.6 0 -20.2 mm

/gate/encapsulatingBox/daughters/name voxel_0126
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0126/geometry/setXLength 0.2 mm
/gate/voxel_0126/geometry/setYLength 1 mm
/gate/voxel_0126/geometry/setZLength 2.0 mm
/gate/voxel_0126/setMaterial Plastic
/gate/voxel_0126/vis/forceSolid
/gate/voxel_0126/vis/setColor yellow
/gate/voxel_0126/placement/setTranslation -6.7 0 -10.0 mm

/gate/encapsulatingBox/daughters/name voxel_0127
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0127/geometry/setXLength 0.2 mm
/gate/voxel_0127/geometry/setYLength 1 mm
/gate/voxel_0127/geometry/setZLength 8.4 mm
/gate/voxel_0127/setMaterial Plastic
/gate/voxel_0127/vis/forceSolid
/gate/voxel_0127/vis/setColor yellow
/gate/voxel_0127/placement/setTranslation -6.7 0 -3.6 mm

/gate/encapsulatingBox/daughters/name voxel_0128
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0128/geometry/setXLength 0.2 mm
/gate/voxel_0128/geometry/setYLength 1 mm
/gate/voxel_0128/geometry/setZLength 2.4 mm
/gate/voxel_0128/setMaterial Plastic
/gate/voxel_0128/vis/forceSolid
/gate/voxel_0128/vis/setColor yellow
/gate/voxel_0128/placement/setTranslation -6.7 0 4.0 mm

/gate/encapsulatingBox/daughters/name voxel_0129
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0129/geometry/setXLength 0.2 mm
/gate/voxel_0129/geometry/setYLength 1 mm
/gate/voxel_0129/geometry/setZLength 1.8 mm
/gate/voxel_0129/setMaterial Plastic
/gate/voxel_0129/vis/forceSolid
/gate/voxel_0129/vis/setColor yellow
/gate/voxel_0129/placement/setTranslation -6.7 0 10.1 mm

/gate/encapsulatingBox/daughters/name voxel_0130
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0130/geometry/setXLength 0.6 mm
/gate/voxel_0130/geometry/setYLength 1 mm
/gate/voxel_0130/geometry/setZLength 1.6 mm
/gate/voxel_0130/setMaterial Plastic
/gate/voxel_0130/vis/forceSolid
/gate/voxel_0130/vis/setColor yellow
/gate/voxel_0130/placement/setTranslation -6.3 0 -14.6 mm

/gate/encapsulatingBox/daughters/name voxel_0131
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0131/geometry/setXLength 0.2 mm
/gate/voxel_0131/geometry/setYLength 1 mm
/gate/voxel_0131/geometry/setZLength 11.6 mm
/gate/voxel_0131/setMaterial Plastic
/gate/voxel_0131/vis/forceSolid
/gate/voxel_0131/vis/setColor yellow
/gate/voxel_0131/placement/setTranslation -6.5 0 -5.2 mm

/gate/encapsulatingBox/daughters/name voxel_0132
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0132/geometry/setXLength 0.2 mm
/gate/voxel_0132/geometry/setYLength 1 mm
/gate/voxel_0132/geometry/setZLength 2.4 mm
/gate/voxel_0132/setMaterial Plastic
/gate/voxel_0132/vis/forceSolid
/gate/voxel_0132/vis/setColor yellow
/gate/voxel_0132/placement/setTranslation -6.5 0 3.8 mm

/gate/encapsulatingBox/daughters/name voxel_0133
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0133/geometry/setXLength 0.2 mm
/gate/voxel_0133/geometry/setYLength 1 mm
/gate/voxel_0133/geometry/setZLength 1.8 mm
/gate/voxel_0133/setMaterial Plastic
/gate/voxel_0133/vis/forceSolid
/gate/voxel_0133/vis/setColor yellow
/gate/voxel_0133/placement/setTranslation -6.5 0 10.3 mm

/gate/encapsulatingBox/daughters/name voxel_0134
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0134/geometry/setXLength 0.4 mm
/gate/voxel_0134/geometry/setYLength 1 mm
/gate/voxel_0134/geometry/setZLength 2.6 mm
/gate/voxel_0134/setMaterial Plastic
/gate/voxel_0134/vis/forceSolid
/gate/voxel_0134/vis/setColor yellow
/gate/voxel_0134/placement/setTranslation -6.2 0 -20.3 mm

/gate/encapsulatingBox/daughters/name voxel_0135
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0135/geometry/setXLength 0.2 mm
/gate/voxel_0135/geometry/setYLength 1 mm
/gate/voxel_0135/geometry/setZLength 12.2 mm
/gate/voxel_0135/setMaterial Plastic
/gate/voxel_0135/vis/forceSolid
/gate/voxel_0135/vis/setColor yellow
/gate/voxel_0135/placement/setTranslation -6.3 0 -5.1 mm

/gate/encapsulatingBox/daughters/name voxel_0136
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0136/geometry/setXLength 0.2 mm
/gate/voxel_0136/geometry/setYLength 1 mm
/gate/voxel_0136/geometry/setZLength 2.4 mm
/gate/voxel_0136/setMaterial Plastic
/gate/voxel_0136/vis/forceSolid
/gate/voxel_0136/vis/setColor yellow
/gate/voxel_0136/placement/setTranslation -6.3 0 3.6 mm

/gate/encapsulatingBox/daughters/name voxel_0137
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0137/geometry/setXLength 0.2 mm
/gate/voxel_0137/geometry/setYLength 1 mm
/gate/voxel_0137/geometry/setZLength 2.0 mm
/gate/voxel_0137/setMaterial Plastic
/gate/voxel_0137/vis/forceSolid
/gate/voxel_0137/vis/setColor yellow
/gate/voxel_0137/placement/setTranslation -6.3 0 10.6 mm

/gate/encapsulatingBox/daughters/name voxel_0138
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0138/geometry/setXLength 0.2 mm
/gate/voxel_0138/geometry/setYLength 1 mm
/gate/voxel_0138/geometry/setZLength 15.8 mm
/gate/voxel_0138/setMaterial Plastic
/gate/voxel_0138/vis/forceSolid
/gate/voxel_0138/vis/setColor yellow
/gate/voxel_0138/placement/setTranslation -6.1 0 -3.3 mm

/gate/encapsulatingBox/daughters/name voxel_0139
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0139/geometry/setXLength 0.2 mm
/gate/voxel_0139/geometry/setYLength 1 mm
/gate/voxel_0139/geometry/setZLength 2.0 mm
/gate/voxel_0139/setMaterial Plastic
/gate/voxel_0139/vis/forceSolid
/gate/voxel_0139/vis/setColor yellow
/gate/voxel_0139/placement/setTranslation -6.1 0 10.8 mm

/gate/encapsulatingBox/daughters/name voxel_0140
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0140/geometry/setXLength 0.4 mm
/gate/voxel_0140/geometry/setYLength 1 mm
/gate/voxel_0140/geometry/setZLength 2.8 mm
/gate/voxel_0140/setMaterial Plastic
/gate/voxel_0140/vis/forceSolid
/gate/voxel_0140/vis/setColor yellow
/gate/voxel_0140/placement/setTranslation -5.8 0 -20.4 mm

/gate/encapsulatingBox/daughters/name voxel_0141
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0141/geometry/setXLength 0.2 mm
/gate/voxel_0141/geometry/setYLength 1 mm
/gate/voxel_0141/geometry/setZLength 1.8 mm
/gate/voxel_0141/setMaterial Plastic
/gate/voxel_0141/vis/forceSolid
/gate/voxel_0141/vis/setColor yellow
/gate/voxel_0141/placement/setTranslation -5.9 0 -14.5 mm

/gate/encapsulatingBox/daughters/name voxel_0142
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0142/geometry/setXLength 0.2 mm
/gate/voxel_0142/geometry/setYLength 1 mm
/gate/voxel_0142/geometry/setZLength 16.2 mm
/gate/voxel_0142/setMaterial Plastic
/gate/voxel_0142/vis/forceSolid
/gate/voxel_0142/vis/setColor yellow
/gate/voxel_0142/placement/setTranslation -5.9 0 -3.5 mm

/gate/encapsulatingBox/daughters/name voxel_0143
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0143/geometry/setXLength 0.2 mm
/gate/voxel_0143/geometry/setYLength 1 mm
/gate/voxel_0143/geometry/setZLength 2.2 mm
/gate/voxel_0143/setMaterial Plastic
/gate/voxel_0143/vis/forceSolid
/gate/voxel_0143/vis/setColor yellow
/gate/voxel_0143/placement/setTranslation -5.9 0 10.9 mm

/gate/encapsulatingBox/daughters/name voxel_0144
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0144/geometry/setXLength 0.2 mm
/gate/voxel_0144/geometry/setYLength 1 mm
/gate/voxel_0144/geometry/setZLength 2.0 mm
/gate/voxel_0144/setMaterial Plastic
/gate/voxel_0144/vis/forceSolid
/gate/voxel_0144/vis/setColor yellow
/gate/voxel_0144/placement/setTranslation -5.7 0 -14.2 mm

/gate/encapsulatingBox/daughters/name voxel_0145
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0145/geometry/setXLength 0.2 mm
/gate/voxel_0145/geometry/setYLength 1 mm
/gate/voxel_0145/geometry/setZLength 16.6 mm
/gate/voxel_0145/setMaterial Plastic
/gate/voxel_0145/vis/forceSolid
/gate/voxel_0145/vis/setColor yellow
/gate/voxel_0145/placement/setTranslation -5.7 0 -3.7 mm

/gate/encapsulatingBox/daughters/name voxel_0146
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0146/geometry/setXLength 0.2 mm
/gate/voxel_0146/geometry/setYLength 1 mm
/gate/voxel_0146/geometry/setZLength 2.2 mm
/gate/voxel_0146/setMaterial Plastic
/gate/voxel_0146/vis/forceSolid
/gate/voxel_0146/vis/setColor yellow
/gate/voxel_0146/placement/setTranslation -5.7 0 11.1 mm

/gate/encapsulatingBox/daughters/name voxel_0147
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0147/geometry/setXLength 0.2 mm
/gate/voxel_0147/geometry/setYLength 1 mm
/gate/voxel_0147/geometry/setZLength 3.0 mm
/gate/voxel_0147/setMaterial Plastic
/gate/voxel_0147/vis/forceSolid
/gate/voxel_0147/vis/setColor yellow
/gate/voxel_0147/placement/setTranslation -5.5 0 -20.5 mm

/gate/encapsulatingBox/daughters/name voxel_0148
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0148/geometry/setXLength 0.4 mm
/gate/voxel_0148/geometry/setYLength 1 mm
/gate/voxel_0148/geometry/setZLength 19.8 mm
/gate/voxel_0148/setMaterial Plastic
/gate/voxel_0148/vis/forceSolid
/gate/voxel_0148/vis/setColor yellow
/gate/voxel_0148/placement/setTranslation -5.4 0 -5.3 mm

/gate/encapsulatingBox/daughters/name voxel_0149
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0149/geometry/setXLength 0.2 mm
/gate/voxel_0149/geometry/setYLength 1 mm
/gate/voxel_0149/geometry/setZLength 2.2 mm
/gate/voxel_0149/setMaterial Plastic
/gate/voxel_0149/vis/forceSolid
/gate/voxel_0149/vis/setColor yellow
/gate/voxel_0149/placement/setTranslation -5.5 0 11.3 mm

/gate/encapsulatingBox/daughters/name voxel_0150
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0150/geometry/setXLength 0.2 mm
/gate/voxel_0150/geometry/setYLength 1 mm
/gate/voxel_0150/geometry/setZLength 3.2 mm
/gate/voxel_0150/setMaterial Plastic
/gate/voxel_0150/vis/forceSolid
/gate/voxel_0150/vis/setColor yellow
/gate/voxel_0150/placement/setTranslation -5.3 0 -20.6 mm

/gate/encapsulatingBox/daughters/name voxel_0151
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0151/geometry/setXLength 0.2 mm
/gate/voxel_0151/geometry/setYLength 1 mm
/gate/voxel_0151/geometry/setZLength 2.2 mm
/gate/voxel_0151/setMaterial Plastic
/gate/voxel_0151/vis/forceSolid
/gate/voxel_0151/vis/setColor yellow
/gate/voxel_0151/placement/setTranslation -5.3 0 11.5 mm

/gate/encapsulatingBox/daughters/name voxel_0152
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0152/geometry/setXLength 0.4 mm
/gate/voxel_0152/geometry/setYLength 1 mm
/gate/voxel_0152/geometry/setZLength 3.4 mm
/gate/voxel_0152/setMaterial Plastic
/gate/voxel_0152/vis/forceSolid
/gate/voxel_0152/vis/setColor yellow
/gate/voxel_0152/placement/setTranslation -5.0 0 -20.7 mm

/gate/encapsulatingBox/daughters/name voxel_0153
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0153/geometry/setXLength 0.2 mm
/gate/voxel_0153/geometry/setYLength 1 mm
/gate/voxel_0153/geometry/setZLength 9.6 mm
/gate/voxel_0153/setMaterial Plastic
/gate/voxel_0153/vis/forceSolid
/gate/voxel_0153/vis/setColor yellow
/gate/voxel_0153/placement/setTranslation -5.1 0 -10.4 mm

/gate/encapsulatingBox/daughters/name voxel_0154
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0154/geometry/setXLength 0.2 mm
/gate/voxel_0154/geometry/setYLength 1 mm
/gate/voxel_0154/geometry/setZLength 10.0 mm
/gate/voxel_0154/setMaterial Plastic
/gate/voxel_0154/vis/forceSolid
/gate/voxel_0154/vis/setColor yellow
/gate/voxel_0154/placement/setTranslation -5.1 0 -0.2 mm

/gate/encapsulatingBox/daughters/name voxel_0155
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0155/geometry/setXLength 0.2 mm
/gate/voxel_0155/geometry/setYLength 1 mm
/gate/voxel_0155/geometry/setZLength 2.2 mm
/gate/voxel_0155/setMaterial Plastic
/gate/voxel_0155/vis/forceSolid
/gate/voxel_0155/vis/setColor yellow
/gate/voxel_0155/placement/setTranslation -5.1 0 11.7 mm

/gate/encapsulatingBox/daughters/name voxel_0156
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0156/geometry/setXLength 0.2 mm
/gate/voxel_0156/geometry/setYLength 1 mm
/gate/voxel_0156/geometry/setZLength 7.8 mm
/gate/voxel_0156/setMaterial Plastic
/gate/voxel_0156/vis/forceSolid
/gate/voxel_0156/vis/setColor yellow
/gate/voxel_0156/placement/setTranslation -4.9 0 -11.3 mm

/gate/encapsulatingBox/daughters/name voxel_0157
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0157/geometry/setXLength 0.2 mm
/gate/voxel_0157/geometry/setYLength 1 mm
/gate/voxel_0157/geometry/setZLength 6.8 mm
/gate/voxel_0157/setMaterial Plastic
/gate/voxel_0157/vis/forceSolid
/gate/voxel_0157/vis/setColor yellow
/gate/voxel_0157/placement/setTranslation -4.9 0 1.6 mm

/gate/encapsulatingBox/daughters/name voxel_0158
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0158/geometry/setXLength 0.2 mm
/gate/voxel_0158/geometry/setYLength 1 mm
/gate/voxel_0158/geometry/setZLength 2.2 mm
/gate/voxel_0158/setMaterial Plastic
/gate/voxel_0158/vis/forceSolid
/gate/voxel_0158/vis/setColor yellow
/gate/voxel_0158/placement/setTranslation -4.9 0 11.9 mm

/gate/encapsulatingBox/daughters/name voxel_0159
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0159/geometry/setXLength 0.6 mm
/gate/voxel_0159/geometry/setYLength 1 mm
/gate/voxel_0159/geometry/setZLength 3.6 mm
/gate/voxel_0159/setMaterial Plastic
/gate/voxel_0159/vis/forceSolid
/gate/voxel_0159/vis/setColor yellow
/gate/voxel_0159/placement/setTranslation -4.5 0 -20.8 mm

/gate/encapsulatingBox/daughters/name voxel_0160
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0160/geometry/setXLength 0.2 mm
/gate/voxel_0160/geometry/setYLength 1 mm
/gate/voxel_0160/geometry/setZLength 7.4 mm
/gate/voxel_0160/setMaterial Plastic
/gate/voxel_0160/vis/forceSolid
/gate/voxel_0160/vis/setColor yellow
/gate/voxel_0160/placement/setTranslation -4.7 0 -11.7 mm

/gate/encapsulatingBox/daughters/name voxel_0161
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0161/geometry/setXLength 0.2 mm
/gate/voxel_0161/geometry/setYLength 1 mm
/gate/voxel_0161/geometry/setZLength 5.6 mm
/gate/voxel_0161/setMaterial Plastic
/gate/voxel_0161/vis/forceSolid
/gate/voxel_0161/vis/setColor yellow
/gate/voxel_0161/placement/setTranslation -4.7 0 2.4 mm

/gate/encapsulatingBox/daughters/name voxel_0162
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0162/geometry/setXLength 0.2 mm
/gate/voxel_0162/geometry/setYLength 1 mm
/gate/voxel_0162/geometry/setZLength 2.2 mm
/gate/voxel_0162/setMaterial Plastic
/gate/voxel_0162/vis/forceSolid
/gate/voxel_0162/vis/setColor yellow
/gate/voxel_0162/placement/setTranslation -4.7 0 12.1 mm

/gate/encapsulatingBox/daughters/name voxel_0163
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0163/geometry/setXLength 0.2 mm
/gate/voxel_0163/geometry/setYLength 1 mm
/gate/voxel_0163/geometry/setZLength 6.6 mm
/gate/voxel_0163/setMaterial Plastic
/gate/voxel_0163/vis/forceSolid
/gate/voxel_0163/vis/setColor yellow
/gate/voxel_0163/placement/setTranslation -4.5 0 -12.1 mm

/gate/encapsulatingBox/daughters/name voxel_0164
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0164/geometry/setXLength 0.2 mm
/gate/voxel_0164/geometry/setYLength 1 mm
/gate/voxel_0164/geometry/setZLength 4.4 mm
/gate/voxel_0164/setMaterial Plastic
/gate/voxel_0164/vis/forceSolid
/gate/voxel_0164/vis/setColor yellow
/gate/voxel_0164/placement/setTranslation -4.5 0 3.2 mm

/gate/encapsulatingBox/daughters/name voxel_0165
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0165/geometry/setXLength 0.2 mm
/gate/voxel_0165/geometry/setYLength 1 mm
/gate/voxel_0165/geometry/setZLength 2.0 mm
/gate/voxel_0165/setMaterial Plastic
/gate/voxel_0165/vis/forceSolid
/gate/voxel_0165/vis/setColor yellow
/gate/voxel_0165/placement/setTranslation -4.5 0 12.2 mm

/gate/encapsulatingBox/daughters/name voxel_0166
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0166/geometry/setXLength 0.2 mm
/gate/voxel_0166/geometry/setYLength 1 mm
/gate/voxel_0166/geometry/setZLength 5.8 mm
/gate/voxel_0166/setMaterial Plastic
/gate/voxel_0166/vis/forceSolid
/gate/voxel_0166/vis/setColor yellow
/gate/voxel_0166/placement/setTranslation -4.3 0 -12.5 mm

/gate/encapsulatingBox/daughters/name voxel_0167
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0167/geometry/setXLength 0.2 mm
/gate/voxel_0167/geometry/setYLength 1 mm
/gate/voxel_0167/geometry/setZLength 4.0 mm
/gate/voxel_0167/setMaterial Plastic
/gate/voxel_0167/vis/forceSolid
/gate/voxel_0167/vis/setColor yellow
/gate/voxel_0167/placement/setTranslation -4.3 0 3.8 mm

/gate/encapsulatingBox/daughters/name voxel_0168
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0168/geometry/setXLength 0.2 mm
/gate/voxel_0168/geometry/setYLength 1 mm
/gate/voxel_0168/geometry/setZLength 2.0 mm
/gate/voxel_0168/setMaterial Plastic
/gate/voxel_0168/vis/forceSolid
/gate/voxel_0168/vis/setColor yellow
/gate/voxel_0168/placement/setTranslation -4.3 0 12.4 mm

/gate/encapsulatingBox/daughters/name voxel_0169
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0169/geometry/setXLength 0.2 mm
/gate/voxel_0169/geometry/setYLength 1 mm
/gate/voxel_0169/geometry/setZLength 3.8 mm
/gate/voxel_0169/setMaterial Plastic
/gate/voxel_0169/vis/forceSolid
/gate/voxel_0169/vis/setColor yellow
/gate/voxel_0169/placement/setTranslation -4.1 0 -20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0170
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0170/geometry/setXLength 0.2 mm
/gate/voxel_0170/geometry/setYLength 1 mm
/gate/voxel_0170/geometry/setZLength 5.6 mm
/gate/voxel_0170/setMaterial Plastic
/gate/voxel_0170/vis/forceSolid
/gate/voxel_0170/vis/setColor yellow
/gate/voxel_0170/placement/setTranslation -4.1 0 -12.8 mm

/gate/encapsulatingBox/daughters/name voxel_0171
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0171/geometry/setXLength 0.2 mm
/gate/voxel_0171/geometry/setYLength 1 mm
/gate/voxel_0171/geometry/setZLength 4.0 mm
/gate/voxel_0171/setMaterial Plastic
/gate/voxel_0171/vis/forceSolid
/gate/voxel_0171/vis/setColor yellow
/gate/voxel_0171/placement/setTranslation -4.1 0 4.2 mm

/gate/encapsulatingBox/daughters/name voxel_0172
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0172/geometry/setXLength 0.2 mm
/gate/voxel_0172/geometry/setYLength 1 mm
/gate/voxel_0172/geometry/setZLength 2.2 mm
/gate/voxel_0172/setMaterial Plastic
/gate/voxel_0172/vis/forceSolid
/gate/voxel_0172/vis/setColor yellow
/gate/voxel_0172/placement/setTranslation -4.1 0 12.5 mm

/gate/encapsulatingBox/daughters/name voxel_0173
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0173/geometry/setXLength 0.6 mm
/gate/voxel_0173/geometry/setYLength 1 mm
/gate/voxel_0173/geometry/setZLength 4.0 mm
/gate/voxel_0173/setMaterial Plastic
/gate/voxel_0173/vis/forceSolid
/gate/voxel_0173/vis/setColor yellow
/gate/voxel_0173/placement/setTranslation -3.7 0 -20.8 mm

/gate/encapsulatingBox/daughters/name voxel_0174
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0174/geometry/setXLength 0.2 mm
/gate/voxel_0174/geometry/setYLength 1 mm
/gate/voxel_0174/geometry/setZLength 5.2 mm
/gate/voxel_0174/setMaterial Plastic
/gate/voxel_0174/vis/forceSolid
/gate/voxel_0174/vis/setColor yellow
/gate/voxel_0174/placement/setTranslation -3.9 0 -13.2 mm

/gate/encapsulatingBox/daughters/name voxel_0175
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0175/geometry/setXLength 0.2 mm
/gate/voxel_0175/geometry/setYLength 1 mm
/gate/voxel_0175/geometry/setZLength 4.0 mm
/gate/voxel_0175/setMaterial Plastic
/gate/voxel_0175/vis/forceSolid
/gate/voxel_0175/vis/setColor yellow
/gate/voxel_0175/placement/setTranslation -3.9 0 4.6 mm

/gate/encapsulatingBox/daughters/name voxel_0176
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0176/geometry/setXLength 0.2 mm
/gate/voxel_0176/geometry/setYLength 1 mm
/gate/voxel_0176/geometry/setZLength 2.4 mm
/gate/voxel_0176/setMaterial Plastic
/gate/voxel_0176/vis/forceSolid
/gate/voxel_0176/vis/setColor yellow
/gate/voxel_0176/placement/setTranslation -3.9 0 12.6 mm

/gate/encapsulatingBox/daughters/name voxel_0177
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0177/geometry/setXLength 0.2 mm
/gate/voxel_0177/geometry/setYLength 1 mm
/gate/voxel_0177/geometry/setZLength 4.8 mm
/gate/voxel_0177/setMaterial Plastic
/gate/voxel_0177/vis/forceSolid
/gate/voxel_0177/vis/setColor yellow
/gate/voxel_0177/placement/setTranslation -3.7 0 -13.6 mm

/gate/encapsulatingBox/daughters/name voxel_0178
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0178/geometry/setXLength 0.2 mm
/gate/voxel_0178/geometry/setYLength 1 mm
/gate/voxel_0178/geometry/setZLength 3.8 mm
/gate/voxel_0178/setMaterial Plastic
/gate/voxel_0178/vis/forceSolid
/gate/voxel_0178/vis/setColor yellow
/gate/voxel_0178/placement/setTranslation -3.7 0 5.1 mm

/gate/encapsulatingBox/daughters/name voxel_0179
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0179/geometry/setXLength 0.2 mm
/gate/voxel_0179/geometry/setYLength 1 mm
/gate/voxel_0179/geometry/setZLength 2.6 mm
/gate/voxel_0179/setMaterial Plastic
/gate/voxel_0179/vis/forceSolid
/gate/voxel_0179/vis/setColor yellow
/gate/voxel_0179/placement/setTranslation -3.7 0 12.7 mm

/gate/encapsulatingBox/daughters/name voxel_0180
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0180/geometry/setXLength 0.2 mm
/gate/voxel_0180/geometry/setYLength 1 mm
/gate/voxel_0180/geometry/setZLength 4.6 mm
/gate/voxel_0180/setMaterial Plastic
/gate/voxel_0180/vis/forceSolid
/gate/voxel_0180/vis/setColor yellow
/gate/voxel_0180/placement/setTranslation -3.5 0 -13.9 mm

/gate/encapsulatingBox/daughters/name voxel_0181
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0181/geometry/setXLength 0.2 mm
/gate/voxel_0181/geometry/setYLength 1 mm
/gate/voxel_0181/geometry/setZLength 3.8 mm
/gate/voxel_0181/setMaterial Plastic
/gate/voxel_0181/vis/forceSolid
/gate/voxel_0181/vis/setColor yellow
/gate/voxel_0181/placement/setTranslation -3.5 0 5.5 mm

/gate/encapsulatingBox/daughters/name voxel_0182
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0182/geometry/setXLength 0.2 mm
/gate/voxel_0182/geometry/setYLength 1 mm
/gate/voxel_0182/geometry/setZLength 2.8 mm
/gate/voxel_0182/setMaterial Plastic
/gate/voxel_0182/vis/forceSolid
/gate/voxel_0182/vis/setColor yellow
/gate/voxel_0182/placement/setTranslation -3.5 0 12.8 mm

/gate/encapsulatingBox/daughters/name voxel_0183
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0183/geometry/setXLength 0.2 mm
/gate/voxel_0183/geometry/setYLength 1 mm
/gate/voxel_0183/geometry/setZLength 4.0 mm
/gate/voxel_0183/setMaterial Plastic
/gate/voxel_0183/vis/forceSolid
/gate/voxel_0183/vis/setColor yellow
/gate/voxel_0183/placement/setTranslation -3.3 0 -20.6 mm

/gate/encapsulatingBox/daughters/name voxel_0184
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0184/geometry/setXLength 0.2 mm
/gate/voxel_0184/geometry/setYLength 1 mm
/gate/voxel_0184/geometry/setZLength 4.4 mm
/gate/voxel_0184/setMaterial Plastic
/gate/voxel_0184/vis/forceSolid
/gate/voxel_0184/vis/setColor yellow
/gate/voxel_0184/placement/setTranslation -3.3 0 -14.2 mm

/gate/encapsulatingBox/daughters/name voxel_0185
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0185/geometry/setXLength 0.2 mm
/gate/voxel_0185/geometry/setYLength 1 mm
/gate/voxel_0185/geometry/setZLength 3.8 mm
/gate/voxel_0185/setMaterial Plastic
/gate/voxel_0185/vis/forceSolid
/gate/voxel_0185/vis/setColor yellow
/gate/voxel_0185/placement/setTranslation -3.3 0 5.9 mm

/gate/encapsulatingBox/daughters/name voxel_0186
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0186/geometry/setXLength 0.2 mm
/gate/voxel_0186/geometry/setYLength 1 mm
/gate/voxel_0186/geometry/setZLength 3.0 mm
/gate/voxel_0186/setMaterial Plastic
/gate/voxel_0186/vis/forceSolid
/gate/voxel_0186/vis/setColor yellow
/gate/voxel_0186/placement/setTranslation -3.3 0 12.9 mm

/gate/encapsulatingBox/daughters/name voxel_0187
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0187/geometry/setXLength 0.2 mm
/gate/voxel_0187/geometry/setYLength 1 mm
/gate/voxel_0187/geometry/setZLength 3.8 mm
/gate/voxel_0187/setMaterial Plastic
/gate/voxel_0187/vis/forceSolid
/gate/voxel_0187/vis/setColor yellow
/gate/voxel_0187/placement/setTranslation -3.1 0 -20.5 mm

/gate/encapsulatingBox/daughters/name voxel_0188
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0188/geometry/setXLength 0.2 mm
/gate/voxel_0188/geometry/setYLength 1 mm
/gate/voxel_0188/geometry/setZLength 4.2 mm
/gate/voxel_0188/setMaterial Plastic
/gate/voxel_0188/vis/forceSolid
/gate/voxel_0188/vis/setColor yellow
/gate/voxel_0188/placement/setTranslation -3.1 0 -14.5 mm

/gate/encapsulatingBox/daughters/name voxel_0189
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0189/geometry/setXLength 0.2 mm
/gate/voxel_0189/geometry/setYLength 1 mm
/gate/voxel_0189/geometry/setZLength 3.4 mm
/gate/voxel_0189/setMaterial Plastic
/gate/voxel_0189/vis/forceSolid
/gate/voxel_0189/vis/setColor yellow
/gate/voxel_0189/placement/setTranslation -3.1 0 6.5 mm

/gate/encapsulatingBox/daughters/name voxel_0190
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0190/geometry/setXLength 0.2 mm
/gate/voxel_0190/geometry/setYLength 1 mm
/gate/voxel_0190/geometry/setZLength 3.4 mm
/gate/voxel_0190/setMaterial Plastic
/gate/voxel_0190/vis/forceSolid
/gate/voxel_0190/vis/setColor yellow
/gate/voxel_0190/placement/setTranslation -3.1 0 12.9 mm

/gate/encapsulatingBox/daughters/name voxel_0191
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0191/geometry/setXLength 0.2 mm
/gate/voxel_0191/geometry/setYLength 1 mm
/gate/voxel_0191/geometry/setZLength 0.4 mm
/gate/voxel_0191/setMaterial Plastic
/gate/voxel_0191/vis/forceSolid
/gate/voxel_0191/vis/setColor yellow
/gate/voxel_0191/placement/setTranslation -2.9 0 -22.8 mm

/gate/encapsulatingBox/daughters/name voxel_0192
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0192/geometry/setXLength 0.2 mm
/gate/voxel_0192/geometry/setYLength 1 mm
/gate/voxel_0192/geometry/setZLength 1.2 mm
/gate/voxel_0192/setMaterial Plastic
/gate/voxel_0192/vis/forceSolid
/gate/voxel_0192/vis/setColor yellow
/gate/voxel_0192/placement/setTranslation -2.9 0 -21.6 mm

/gate/encapsulatingBox/daughters/name voxel_0193
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0193/geometry/setXLength 0.2 mm
/gate/voxel_0193/geometry/setYLength 1 mm
/gate/voxel_0193/geometry/setZLength 2.0 mm
/gate/voxel_0193/setMaterial Plastic
/gate/voxel_0193/vis/forceSolid
/gate/voxel_0193/vis/setColor yellow
/gate/voxel_0193/placement/setTranslation -2.9 0 -19.4 mm

/gate/encapsulatingBox/daughters/name voxel_0194
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0194/geometry/setXLength 0.2 mm
/gate/voxel_0194/geometry/setYLength 1 mm
/gate/voxel_0194/geometry/setZLength 4.0 mm
/gate/voxel_0194/setMaterial Plastic
/gate/voxel_0194/vis/forceSolid
/gate/voxel_0194/vis/setColor yellow
/gate/voxel_0194/placement/setTranslation -2.9 0 -14.8 mm

/gate/encapsulatingBox/daughters/name voxel_0195
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0195/geometry/setXLength 0.2 mm
/gate/voxel_0195/geometry/setYLength 1 mm
/gate/voxel_0195/geometry/setZLength 3.2 mm
/gate/voxel_0195/setMaterial Plastic
/gate/voxel_0195/vis/forceSolid
/gate/voxel_0195/vis/setColor yellow
/gate/voxel_0195/placement/setTranslation -2.9 0 7.0 mm

/gate/encapsulatingBox/daughters/name voxel_0196
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0196/geometry/setXLength 0.2 mm
/gate/voxel_0196/geometry/setYLength 1 mm
/gate/voxel_0196/geometry/setZLength 3.6 mm
/gate/voxel_0196/setMaterial Plastic
/gate/voxel_0196/vis/forceSolid
/gate/voxel_0196/vis/setColor yellow
/gate/voxel_0196/placement/setTranslation -2.9 0 13.0 mm

/gate/encapsulatingBox/daughters/name voxel_0197
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0197/geometry/setXLength 0.2 mm
/gate/voxel_0197/geometry/setYLength 1 mm
/gate/voxel_0197/geometry/setZLength 0.8 mm
/gate/voxel_0197/setMaterial Plastic
/gate/voxel_0197/vis/forceSolid
/gate/voxel_0197/vis/setColor yellow
/gate/voxel_0197/placement/setTranslation -2.7 0 -22.8 mm

/gate/encapsulatingBox/daughters/name voxel_0198
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0198/geometry/setXLength 0.2 mm
/gate/voxel_0198/geometry/setYLength 1 mm
/gate/voxel_0198/geometry/setZLength 0.6 mm
/gate/voxel_0198/setMaterial Plastic
/gate/voxel_0198/vis/forceSolid
/gate/voxel_0198/vis/setColor yellow
/gate/voxel_0198/placement/setTranslation -2.7 0 -21.5 mm

/gate/encapsulatingBox/daughters/name voxel_0199
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0199/geometry/setXLength 0.2 mm
/gate/voxel_0199/geometry/setYLength 1 mm
/gate/voxel_0199/geometry/setZLength 1.8 mm
/gate/voxel_0199/setMaterial Plastic
/gate/voxel_0199/vis/forceSolid
/gate/voxel_0199/vis/setColor yellow
/gate/voxel_0199/placement/setTranslation -2.7 0 -19.1 mm

/gate/encapsulatingBox/daughters/name voxel_0200
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0200/geometry/setXLength 0.2 mm
/gate/voxel_0200/geometry/setYLength 1 mm
/gate/voxel_0200/geometry/setZLength 2.2 mm
/gate/voxel_0200/setMaterial Plastic
/gate/voxel_0200/vis/forceSolid
/gate/voxel_0200/vis/setColor yellow
/gate/voxel_0200/placement/setTranslation -2.7 0 -15.9 mm

/gate/encapsulatingBox/daughters/name voxel_0201
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0201/geometry/setXLength 0.2 mm
/gate/voxel_0201/geometry/setYLength 1 mm
/gate/voxel_0201/geometry/setZLength 1.2 mm
/gate/voxel_0201/setMaterial Plastic
/gate/voxel_0201/vis/forceSolid
/gate/voxel_0201/vis/setColor yellow
/gate/voxel_0201/placement/setTranslation -2.7 0 -13.8 mm

/gate/encapsulatingBox/daughters/name voxel_0202
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0202/geometry/setXLength 0.2 mm
/gate/voxel_0202/geometry/setYLength 1 mm
/gate/voxel_0202/geometry/setZLength 3.2 mm
/gate/voxel_0202/setMaterial Plastic
/gate/voxel_0202/vis/forceSolid
/gate/voxel_0202/vis/setColor yellow
/gate/voxel_0202/placement/setTranslation -2.7 0 7.4 mm

/gate/encapsulatingBox/daughters/name voxel_0203
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0203/geometry/setXLength 0.2 mm
/gate/voxel_0203/geometry/setYLength 1 mm
/gate/voxel_0203/geometry/setZLength 4.0 mm
/gate/voxel_0203/setMaterial Plastic
/gate/voxel_0203/vis/forceSolid
/gate/voxel_0203/vis/setColor yellow
/gate/voxel_0203/placement/setTranslation -2.7 0 13.0 mm

/gate/encapsulatingBox/daughters/name voxel_0204
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0204/geometry/setXLength 0.2 mm
/gate/voxel_0204/geometry/setYLength 1 mm
/gate/voxel_0204/geometry/setZLength 1.0 mm
/gate/voxel_0204/setMaterial Plastic
/gate/voxel_0204/vis/forceSolid
/gate/voxel_0204/vis/setColor yellow
/gate/voxel_0204/placement/setTranslation -2.5 0 -22.7 mm

/gate/encapsulatingBox/daughters/name voxel_0205
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0205/geometry/setXLength 0.2 mm
/gate/voxel_0205/geometry/setYLength 1 mm
/gate/voxel_0205/geometry/setZLength 4.8 mm
/gate/voxel_0205/setMaterial Plastic
/gate/voxel_0205/vis/forceSolid
/gate/voxel_0205/vis/setColor yellow
/gate/voxel_0205/placement/setTranslation -2.5 0 -17.2 mm

/gate/encapsulatingBox/daughters/name voxel_0206
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0206/geometry/setXLength 0.2 mm
/gate/voxel_0206/geometry/setYLength 1 mm
/gate/voxel_0206/geometry/setZLength 1.0 mm
/gate/voxel_0206/setMaterial Plastic
/gate/voxel_0206/vis/forceSolid
/gate/voxel_0206/vis/setColor yellow
/gate/voxel_0206/placement/setTranslation -2.5 0 -13.9 mm

/gate/encapsulatingBox/daughters/name voxel_0207
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0207/geometry/setXLength 0.2 mm
/gate/voxel_0207/geometry/setYLength 1 mm
/gate/voxel_0207/geometry/setZLength 3.8 mm
/gate/voxel_0207/setMaterial Plastic
/gate/voxel_0207/vis/forceSolid
/gate/voxel_0207/vis/setColor yellow
/gate/voxel_0207/placement/setTranslation -2.5 0 8.1 mm

/gate/encapsulatingBox/daughters/name voxel_0208
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0208/geometry/setXLength 0.2 mm
/gate/voxel_0208/geometry/setYLength 1 mm
/gate/voxel_0208/geometry/setZLength 4.8 mm
/gate/voxel_0208/setMaterial Plastic
/gate/voxel_0208/vis/forceSolid
/gate/voxel_0208/vis/setColor yellow
/gate/voxel_0208/placement/setTranslation -2.5 0 12.8 mm

/gate/encapsulatingBox/daughters/name voxel_0209
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0209/geometry/setXLength 0.2 mm
/gate/voxel_0209/geometry/setYLength 1 mm
/gate/voxel_0209/geometry/setZLength 1.2 mm
/gate/voxel_0209/setMaterial Plastic
/gate/voxel_0209/vis/forceSolid
/gate/voxel_0209/vis/setColor yellow
/gate/voxel_0209/placement/setTranslation -2.3 0 -22.6 mm

/gate/encapsulatingBox/daughters/name voxel_0210
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0210/geometry/setXLength 0.2 mm
/gate/voxel_0210/geometry/setYLength 1 mm
/gate/voxel_0210/geometry/setZLength 4.6 mm
/gate/voxel_0210/setMaterial Plastic
/gate/voxel_0210/vis/forceSolid
/gate/voxel_0210/vis/setColor yellow
/gate/voxel_0210/placement/setTranslation -2.3 0 -17.1 mm

/gate/encapsulatingBox/daughters/name voxel_0211
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0211/geometry/setXLength 0.2 mm
/gate/voxel_0211/geometry/setYLength 1 mm
/gate/voxel_0211/geometry/setZLength 0.6 mm
/gate/voxel_0211/setMaterial Plastic
/gate/voxel_0211/vis/forceSolid
/gate/voxel_0211/vis/setColor yellow
/gate/voxel_0211/placement/setTranslation -2.3 0 -13.9 mm

/gate/encapsulatingBox/daughters/name voxel_0212
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0212/geometry/setXLength 0.2 mm
/gate/voxel_0212/geometry/setYLength 1 mm
/gate/voxel_0212/geometry/setZLength 5.8 mm
/gate/voxel_0212/setMaterial Plastic
/gate/voxel_0212/vis/forceSolid
/gate/voxel_0212/vis/setColor yellow
/gate/voxel_0212/placement/setTranslation -2.3 0 9.5 mm

/gate/encapsulatingBox/daughters/name voxel_0213
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0213/geometry/setXLength 0.2 mm
/gate/voxel_0213/geometry/setYLength 1 mm
/gate/voxel_0213/geometry/setZLength 2.0 mm
/gate/voxel_0213/setMaterial Plastic
/gate/voxel_0213/vis/forceSolid
/gate/voxel_0213/vis/setColor yellow
/gate/voxel_0213/placement/setTranslation -2.3 0 14.4 mm

/gate/encapsulatingBox/daughters/name voxel_0214
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0214/geometry/setXLength 0.4 mm
/gate/voxel_0214/geometry/setYLength 1 mm
/gate/voxel_0214/geometry/setZLength 1.4 mm
/gate/voxel_0214/setMaterial Plastic
/gate/voxel_0214/vis/forceSolid
/gate/voxel_0214/vis/setColor yellow
/gate/voxel_0214/placement/setTranslation -2.0 0 -22.5 mm

/gate/encapsulatingBox/daughters/name voxel_0215
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0215/geometry/setXLength 0.4 mm
/gate/voxel_0215/geometry/setYLength 1 mm
/gate/voxel_0215/geometry/setZLength 4.4 mm
/gate/voxel_0215/setMaterial Plastic
/gate/voxel_0215/vis/forceSolid
/gate/voxel_0215/vis/setColor yellow
/gate/voxel_0215/placement/setTranslation -2.0 0 -17.0 mm

/gate/encapsulatingBox/daughters/name voxel_0216
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0216/geometry/setXLength 0.2 mm
/gate/voxel_0216/geometry/setYLength 1 mm
/gate/voxel_0216/geometry/setZLength 5.4 mm
/gate/voxel_0216/setMaterial Plastic
/gate/voxel_0216/vis/forceSolid
/gate/voxel_0216/vis/setColor yellow
/gate/voxel_0216/placement/setTranslation -2.1 0 9.5 mm

/gate/encapsulatingBox/daughters/name voxel_0217
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0217/geometry/setXLength 0.2 mm
/gate/voxel_0217/geometry/setYLength 1 mm
/gate/voxel_0217/geometry/setZLength 2.0 mm
/gate/voxel_0217/setMaterial Plastic
/gate/voxel_0217/vis/forceSolid
/gate/voxel_0217/vis/setColor yellow
/gate/voxel_0217/placement/setTranslation -2.1 0 14.6 mm

/gate/encapsulatingBox/daughters/name voxel_0218
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0218/geometry/setXLength 0.2 mm
/gate/voxel_0218/geometry/setYLength 1 mm
/gate/voxel_0218/geometry/setZLength 4.8 mm
/gate/voxel_0218/setMaterial Plastic
/gate/voxel_0218/vis/forceSolid
/gate/voxel_0218/vis/setColor yellow
/gate/voxel_0218/placement/setTranslation -1.9 0 9.6 mm

/gate/encapsulatingBox/daughters/name voxel_0219
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0219/geometry/setXLength 0.2 mm
/gate/voxel_0219/geometry/setYLength 1 mm
/gate/voxel_0219/geometry/setZLength 2.0 mm
/gate/voxel_0219/setMaterial Plastic
/gate/voxel_0219/vis/forceSolid
/gate/voxel_0219/vis/setColor yellow
/gate/voxel_0219/placement/setTranslation -1.9 0 14.8 mm

/gate/encapsulatingBox/daughters/name voxel_0220
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0220/geometry/setXLength 1.4 mm
/gate/voxel_0220/geometry/setYLength 1 mm
/gate/voxel_0220/geometry/setZLength 1.6 mm
/gate/voxel_0220/setMaterial Plastic
/gate/voxel_0220/vis/forceSolid
/gate/voxel_0220/vis/setColor yellow
/gate/voxel_0220/placement/setTranslation -1.1 0 -22.6 mm

/gate/encapsulatingBox/daughters/name voxel_0221
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0221/geometry/setXLength 0.2 mm
/gate/voxel_0221/geometry/setYLength 1 mm
/gate/voxel_0221/geometry/setZLength 4.0 mm
/gate/voxel_0221/setMaterial Plastic
/gate/voxel_0221/vis/forceSolid
/gate/voxel_0221/vis/setColor yellow
/gate/voxel_0221/placement/setTranslation -1.7 0 -17.0 mm

/gate/encapsulatingBox/daughters/name voxel_0222
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0222/geometry/setXLength 0.2 mm
/gate/voxel_0222/geometry/setYLength 1 mm
/gate/voxel_0222/geometry/setZLength 4.2 mm
/gate/voxel_0222/setMaterial Plastic
/gate/voxel_0222/vis/forceSolid
/gate/voxel_0222/vis/setColor yellow
/gate/voxel_0222/placement/setTranslation -1.7 0 9.7 mm

/gate/encapsulatingBox/daughters/name voxel_0223
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0223/geometry/setXLength 0.2 mm
/gate/voxel_0223/geometry/setYLength 1 mm
/gate/voxel_0223/geometry/setZLength 1.8 mm
/gate/voxel_0223/setMaterial Plastic
/gate/voxel_0223/vis/forceSolid
/gate/voxel_0223/vis/setColor yellow
/gate/voxel_0223/placement/setTranslation -1.7 0 14.9 mm

/gate/encapsulatingBox/daughters/name voxel_0224
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0224/geometry/setXLength 0.2 mm
/gate/voxel_0224/geometry/setYLength 1 mm
/gate/voxel_0224/geometry/setZLength 3.8 mm
/gate/voxel_0224/setMaterial Plastic
/gate/voxel_0224/vis/forceSolid
/gate/voxel_0224/vis/setColor yellow
/gate/voxel_0224/placement/setTranslation -1.5 0 -17.1 mm

/gate/encapsulatingBox/daughters/name voxel_0225
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0225/geometry/setXLength 0.2 mm
/gate/voxel_0225/geometry/setYLength 1 mm
/gate/voxel_0225/geometry/setZLength 4.0 mm
/gate/voxel_0225/setMaterial Plastic
/gate/voxel_0225/vis/forceSolid
/gate/voxel_0225/vis/setColor yellow
/gate/voxel_0225/placement/setTranslation -1.5 0 9.8 mm

/gate/encapsulatingBox/daughters/name voxel_0226
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0226/geometry/setXLength 0.2 mm
/gate/voxel_0226/geometry/setYLength 1 mm
/gate/voxel_0226/geometry/setZLength 1.8 mm
/gate/voxel_0226/setMaterial Plastic
/gate/voxel_0226/vis/forceSolid
/gate/voxel_0226/vis/setColor yellow
/gate/voxel_0226/placement/setTranslation -1.5 0 15.1 mm

/gate/encapsulatingBox/daughters/name voxel_0227
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0227/geometry/setXLength 0.2 mm
/gate/voxel_0227/geometry/setYLength 1 mm
/gate/voxel_0227/geometry/setZLength 3.6 mm
/gate/voxel_0227/setMaterial Plastic
/gate/voxel_0227/vis/forceSolid
/gate/voxel_0227/vis/setColor yellow
/gate/voxel_0227/placement/setTranslation -1.3 0 -17.2 mm

/gate/encapsulatingBox/daughters/name voxel_0228
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0228/geometry/setXLength 0.2 mm
/gate/voxel_0228/geometry/setYLength 1 mm
/gate/voxel_0228/geometry/setZLength 3.8 mm
/gate/voxel_0228/setMaterial Plastic
/gate/voxel_0228/vis/forceSolid
/gate/voxel_0228/vis/setColor yellow
/gate/voxel_0228/placement/setTranslation -1.3 0 9.9 mm

/gate/encapsulatingBox/daughters/name voxel_0229
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0229/geometry/setXLength 0.2 mm
/gate/voxel_0229/geometry/setYLength 1 mm
/gate/voxel_0229/geometry/setZLength 1.8 mm
/gate/voxel_0229/setMaterial Plastic
/gate/voxel_0229/vis/forceSolid
/gate/voxel_0229/vis/setColor yellow
/gate/voxel_0229/placement/setTranslation -1.3 0 15.3 mm

/gate/encapsulatingBox/daughters/name voxel_0230
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0230/geometry/setXLength 0.2 mm
/gate/voxel_0230/geometry/setYLength 1 mm
/gate/voxel_0230/geometry/setZLength 3.4 mm
/gate/voxel_0230/setMaterial Plastic
/gate/voxel_0230/vis/forceSolid
/gate/voxel_0230/vis/setColor yellow
/gate/voxel_0230/placement/setTranslation -1.1 0 -17.3 mm

/gate/encapsulatingBox/daughters/name voxel_0231
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0231/geometry/setXLength 0.2 mm
/gate/voxel_0231/geometry/setYLength 1 mm
/gate/voxel_0231/geometry/setZLength 3.4 mm
/gate/voxel_0231/setMaterial Plastic
/gate/voxel_0231/vis/forceSolid
/gate/voxel_0231/vis/setColor yellow
/gate/voxel_0231/placement/setTranslation -1.1 0 10.1 mm

/gate/encapsulatingBox/daughters/name voxel_0232
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0232/geometry/setXLength 0.2 mm
/gate/voxel_0232/geometry/setYLength 1 mm
/gate/voxel_0232/geometry/setZLength 1.8 mm
/gate/voxel_0232/setMaterial Plastic
/gate/voxel_0232/vis/forceSolid
/gate/voxel_0232/vis/setColor yellow
/gate/voxel_0232/placement/setTranslation -1.1 0 15.5 mm

/gate/encapsulatingBox/daughters/name voxel_0233
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0233/geometry/setXLength 0.2 mm
/gate/voxel_0233/geometry/setYLength 1 mm
/gate/voxel_0233/geometry/setZLength 3.2 mm
/gate/voxel_0233/setMaterial Plastic
/gate/voxel_0233/vis/forceSolid
/gate/voxel_0233/vis/setColor yellow
/gate/voxel_0233/placement/setTranslation -0.9 0 -17.4 mm

/gate/encapsulatingBox/daughters/name voxel_0234
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0234/geometry/setXLength 0.2 mm
/gate/voxel_0234/geometry/setYLength 1 mm
/gate/voxel_0234/geometry/setZLength 3.2 mm
/gate/voxel_0234/setMaterial Plastic
/gate/voxel_0234/vis/forceSolid
/gate/voxel_0234/vis/setColor yellow
/gate/voxel_0234/placement/setTranslation -0.9 0 10.4 mm

/gate/encapsulatingBox/daughters/name voxel_0235
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0235/geometry/setXLength 0.2 mm
/gate/voxel_0235/geometry/setYLength 1 mm
/gate/voxel_0235/geometry/setZLength 1.8 mm
/gate/voxel_0235/setMaterial Plastic
/gate/voxel_0235/vis/forceSolid
/gate/voxel_0235/vis/setColor yellow
/gate/voxel_0235/placement/setTranslation -0.9 0 15.7 mm

/gate/encapsulatingBox/daughters/name voxel_0236
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0236/geometry/setXLength 0.2 mm
/gate/voxel_0236/geometry/setYLength 1 mm
/gate/voxel_0236/geometry/setZLength 3.0 mm
/gate/voxel_0236/setMaterial Plastic
/gate/voxel_0236/vis/forceSolid
/gate/voxel_0236/vis/setColor yellow
/gate/voxel_0236/placement/setTranslation -0.7 0 -17.5 mm

/gate/encapsulatingBox/daughters/name voxel_0237
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0237/geometry/setXLength 0.2 mm
/gate/voxel_0237/geometry/setYLength 1 mm
/gate/voxel_0237/geometry/setZLength 3.0 mm
/gate/voxel_0237/setMaterial Plastic
/gate/voxel_0237/vis/forceSolid
/gate/voxel_0237/vis/setColor yellow
/gate/voxel_0237/placement/setTranslation -0.7 0 10.5 mm

/gate/encapsulatingBox/daughters/name voxel_0238
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0238/geometry/setXLength 0.2 mm
/gate/voxel_0238/geometry/setYLength 1 mm
/gate/voxel_0238/geometry/setZLength 1.6 mm
/gate/voxel_0238/setMaterial Plastic
/gate/voxel_0238/vis/forceSolid
/gate/voxel_0238/vis/setColor yellow
/gate/voxel_0238/placement/setTranslation -0.7 0 16.0 mm

/gate/encapsulatingBox/daughters/name voxel_0239
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0239/geometry/setXLength 0.2 mm
/gate/voxel_0239/geometry/setYLength 1 mm
/gate/voxel_0239/geometry/setZLength 2.8 mm
/gate/voxel_0239/setMaterial Plastic
/gate/voxel_0239/vis/forceSolid
/gate/voxel_0239/vis/setColor yellow
/gate/voxel_0239/placement/setTranslation -0.5 0 -17.8 mm

/gate/encapsulatingBox/daughters/name voxel_0240
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0240/geometry/setXLength 0.2 mm
/gate/voxel_0240/geometry/setYLength 1 mm
/gate/voxel_0240/geometry/setZLength 2.8 mm
/gate/voxel_0240/setMaterial Plastic
/gate/voxel_0240/vis/forceSolid
/gate/voxel_0240/vis/setColor yellow
/gate/voxel_0240/placement/setTranslation -0.5 0 10.8 mm

/gate/encapsulatingBox/daughters/name voxel_0241
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0241/geometry/setXLength 0.2 mm
/gate/voxel_0241/geometry/setYLength 1 mm
/gate/voxel_0241/geometry/setZLength 1.6 mm
/gate/voxel_0241/setMaterial Plastic
/gate/voxel_0241/vis/forceSolid
/gate/voxel_0241/vis/setColor yellow
/gate/voxel_0241/placement/setTranslation -0.5 0 16.2 mm

/gate/encapsulatingBox/daughters/name voxel_0242
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0242/geometry/setXLength 0.2 mm
/gate/voxel_0242/geometry/setYLength 1 mm
/gate/voxel_0242/geometry/setZLength 1.8 mm
/gate/voxel_0242/setMaterial Plastic
/gate/voxel_0242/vis/forceSolid
/gate/voxel_0242/vis/setColor yellow
/gate/voxel_0242/placement/setTranslation -0.3 0 -22.5 mm

/gate/encapsulatingBox/daughters/name voxel_0243
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0243/geometry/setXLength 0.2 mm
/gate/voxel_0243/geometry/setYLength 1 mm
/gate/voxel_0243/geometry/setZLength 3.0 mm
/gate/voxel_0243/setMaterial Plastic
/gate/voxel_0243/vis/forceSolid
/gate/voxel_0243/vis/setColor yellow
/gate/voxel_0243/placement/setTranslation -0.3 0 -18.1 mm

/gate/encapsulatingBox/daughters/name voxel_0244
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0244/geometry/setXLength 0.2 mm
/gate/voxel_0244/geometry/setYLength 1 mm
/gate/voxel_0244/geometry/setZLength 2.4 mm
/gate/voxel_0244/setMaterial Plastic
/gate/voxel_0244/vis/forceSolid
/gate/voxel_0244/vis/setColor yellow
/gate/voxel_0244/placement/setTranslation -0.3 0 11.2 mm

/gate/encapsulatingBox/daughters/name voxel_0245
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0245/geometry/setXLength 0.2 mm
/gate/voxel_0245/geometry/setYLength 1 mm
/gate/voxel_0245/geometry/setZLength 1.6 mm
/gate/voxel_0245/setMaterial Plastic
/gate/voxel_0245/vis/forceSolid
/gate/voxel_0245/vis/setColor yellow
/gate/voxel_0245/placement/setTranslation -0.3 0 16.4 mm

/gate/encapsulatingBox/daughters/name voxel_0246
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0246/geometry/setXLength 0.2 mm
/gate/voxel_0246/geometry/setYLength 1 mm
/gate/voxel_0246/geometry/setZLength 2.0 mm
/gate/voxel_0246/setMaterial Plastic
/gate/voxel_0246/vis/forceSolid
/gate/voxel_0246/vis/setColor yellow
/gate/voxel_0246/placement/setTranslation -0.1 0 -22.4 mm

/gate/encapsulatingBox/daughters/name voxel_0247
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0247/geometry/setXLength 0.2 mm
/gate/voxel_0247/geometry/setYLength 1 mm
/gate/voxel_0247/geometry/setZLength 3.0 mm
/gate/voxel_0247/setMaterial Plastic
/gate/voxel_0247/vis/forceSolid
/gate/voxel_0247/vis/setColor yellow
/gate/voxel_0247/placement/setTranslation -0.1 0 -18.3 mm

/gate/encapsulatingBox/daughters/name voxel_0248
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0248/geometry/setXLength 0.2 mm
/gate/voxel_0248/geometry/setYLength 1 mm
/gate/voxel_0248/geometry/setZLength 2.4 mm
/gate/voxel_0248/setMaterial Plastic
/gate/voxel_0248/vis/forceSolid
/gate/voxel_0248/vis/setColor yellow
/gate/voxel_0248/placement/setTranslation -0.1 0 11.4 mm

/gate/encapsulatingBox/daughters/name voxel_0249
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0249/geometry/setXLength 0.2 mm
/gate/voxel_0249/geometry/setYLength 1 mm
/gate/voxel_0249/geometry/setZLength 1.2 mm
/gate/voxel_0249/setMaterial Plastic
/gate/voxel_0249/vis/forceSolid
/gate/voxel_0249/vis/setColor yellow
/gate/voxel_0249/placement/setTranslation -0.1 0 16.6 mm

/gate/encapsulatingBox/daughters/name voxel_0250
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0250/geometry/setXLength 0.2 mm
/gate/voxel_0250/geometry/setYLength 1 mm
/gate/voxel_0250/geometry/setZLength 2.0 mm
/gate/voxel_0250/setMaterial Plastic
/gate/voxel_0250/vis/forceSolid
/gate/voxel_0250/vis/setColor yellow
/gate/voxel_0250/placement/setTranslation 0.1 0 -22.2 mm

/gate/encapsulatingBox/daughters/name voxel_0251
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0251/geometry/setXLength 0.2 mm
/gate/voxel_0251/geometry/setYLength 1 mm
/gate/voxel_0251/geometry/setZLength 3.0 mm
/gate/voxel_0251/setMaterial Plastic
/gate/voxel_0251/vis/forceSolid
/gate/voxel_0251/vis/setColor yellow
/gate/voxel_0251/placement/setTranslation 0.1 0 -18.5 mm

/gate/encapsulatingBox/daughters/name voxel_0252
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0252/geometry/setXLength 0.2 mm
/gate/voxel_0252/geometry/setYLength 1 mm
/gate/voxel_0252/geometry/setZLength 2.2 mm
/gate/voxel_0252/setMaterial Plastic
/gate/voxel_0252/vis/forceSolid
/gate/voxel_0252/vis/setColor yellow
/gate/voxel_0252/placement/setTranslation 0.1 0 11.7 mm

/gate/encapsulatingBox/daughters/name voxel_0253
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0253/geometry/setXLength 0.2 mm
/gate/voxel_0253/geometry/setYLength 1 mm
/gate/voxel_0253/geometry/setZLength 1.2 mm
/gate/voxel_0253/setMaterial Plastic
/gate/voxel_0253/vis/forceSolid
/gate/voxel_0253/vis/setColor yellow
/gate/voxel_0253/placement/setTranslation 0.1 0 16.8 mm

/gate/encapsulatingBox/daughters/name voxel_0254
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0254/geometry/setXLength 0.2 mm
/gate/voxel_0254/geometry/setYLength 1 mm
/gate/voxel_0254/geometry/setZLength 5.8 mm
/gate/voxel_0254/setMaterial Plastic
/gate/voxel_0254/vis/forceSolid
/gate/voxel_0254/vis/setColor yellow
/gate/voxel_0254/placement/setTranslation 0.3 0 -20.3 mm

/gate/encapsulatingBox/daughters/name voxel_0255
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0255/geometry/setXLength 0.2 mm
/gate/voxel_0255/geometry/setYLength 1 mm
/gate/voxel_0255/geometry/setZLength 2.2 mm
/gate/voxel_0255/setMaterial Plastic
/gate/voxel_0255/vis/forceSolid
/gate/voxel_0255/vis/setColor yellow
/gate/voxel_0255/placement/setTranslation 0.3 0 12.1 mm

/gate/encapsulatingBox/daughters/name voxel_0256
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0256/geometry/setXLength 0.2 mm
/gate/voxel_0256/geometry/setYLength 1 mm
/gate/voxel_0256/geometry/setZLength 1.2 mm
/gate/voxel_0256/setMaterial Plastic
/gate/voxel_0256/vis/forceSolid
/gate/voxel_0256/vis/setColor yellow
/gate/voxel_0256/placement/setTranslation 0.3 0 17.0 mm

/gate/encapsulatingBox/daughters/name voxel_0257
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0257/geometry/setXLength 0.2 mm
/gate/voxel_0257/geometry/setYLength 1 mm
/gate/voxel_0257/geometry/setZLength 5.6 mm
/gate/voxel_0257/setMaterial Plastic
/gate/voxel_0257/vis/forceSolid
/gate/voxel_0257/vis/setColor yellow
/gate/voxel_0257/placement/setTranslation 0.5 0 -20.4 mm

/gate/encapsulatingBox/daughters/name voxel_0258
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0258/geometry/setXLength 0.2 mm
/gate/voxel_0258/geometry/setYLength 1 mm
/gate/voxel_0258/geometry/setZLength 2.2 mm
/gate/voxel_0258/setMaterial Plastic
/gate/voxel_0258/vis/forceSolid
/gate/voxel_0258/vis/setColor yellow
/gate/voxel_0258/placement/setTranslation 0.5 0 12.3 mm

/gate/encapsulatingBox/daughters/name voxel_0259
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0259/geometry/setXLength 0.2 mm
/gate/voxel_0259/geometry/setYLength 1 mm
/gate/voxel_0259/geometry/setZLength 1.2 mm
/gate/voxel_0259/setMaterial Plastic
/gate/voxel_0259/vis/forceSolid
/gate/voxel_0259/vis/setColor yellow
/gate/voxel_0259/placement/setTranslation 0.5 0 17.2 mm

/gate/encapsulatingBox/daughters/name voxel_0260
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0260/geometry/setXLength 0.2 mm
/gate/voxel_0260/geometry/setYLength 1 mm
/gate/voxel_0260/geometry/setZLength 5.0 mm
/gate/voxel_0260/setMaterial Plastic
/gate/voxel_0260/vis/forceSolid
/gate/voxel_0260/vis/setColor yellow
/gate/voxel_0260/placement/setTranslation 0.7 0 -20.5 mm

/gate/encapsulatingBox/daughters/name voxel_0261
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0261/geometry/setXLength 0.2 mm
/gate/voxel_0261/geometry/setYLength 1 mm
/gate/voxel_0261/geometry/setZLength 2.2 mm
/gate/voxel_0261/setMaterial Plastic
/gate/voxel_0261/vis/forceSolid
/gate/voxel_0261/vis/setColor yellow
/gate/voxel_0261/placement/setTranslation 0.7 0 12.5 mm

/gate/encapsulatingBox/daughters/name voxel_0262
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0262/geometry/setXLength 0.2 mm
/gate/voxel_0262/geometry/setYLength 1 mm
/gate/voxel_0262/geometry/setZLength 1.4 mm
/gate/voxel_0262/setMaterial Plastic
/gate/voxel_0262/vis/forceSolid
/gate/voxel_0262/vis/setColor yellow
/gate/voxel_0262/placement/setTranslation 0.7 0 17.3 mm

/gate/encapsulatingBox/daughters/name voxel_0263
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0263/geometry/setXLength 0.2 mm
/gate/voxel_0263/geometry/setYLength 1 mm
/gate/voxel_0263/geometry/setZLength 4.8 mm
/gate/voxel_0263/setMaterial Plastic
/gate/voxel_0263/vis/forceSolid
/gate/voxel_0263/vis/setColor yellow
/gate/voxel_0263/placement/setTranslation 0.9 0 -20.6 mm

/gate/encapsulatingBox/daughters/name voxel_0264
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0264/geometry/setXLength 0.2 mm
/gate/voxel_0264/geometry/setYLength 1 mm
/gate/voxel_0264/geometry/setZLength 2.2 mm
/gate/voxel_0264/setMaterial Plastic
/gate/voxel_0264/vis/forceSolid
/gate/voxel_0264/vis/setColor yellow
/gate/voxel_0264/placement/setTranslation 0.9 0 12.9 mm

/gate/encapsulatingBox/daughters/name voxel_0265
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0265/geometry/setXLength 0.2 mm
/gate/voxel_0265/geometry/setYLength 1 mm
/gate/voxel_0265/geometry/setZLength 1.4 mm
/gate/voxel_0265/setMaterial Plastic
/gate/voxel_0265/vis/forceSolid
/gate/voxel_0265/vis/setColor yellow
/gate/voxel_0265/placement/setTranslation 0.9 0 17.5 mm

/gate/encapsulatingBox/daughters/name voxel_0266
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0266/geometry/setXLength 0.2 mm
/gate/voxel_0266/geometry/setYLength 1 mm
/gate/voxel_0266/geometry/setZLength 4.6 mm
/gate/voxel_0266/setMaterial Plastic
/gate/voxel_0266/vis/forceSolid
/gate/voxel_0266/vis/setColor yellow
/gate/voxel_0266/placement/setTranslation 1.1 0 -20.7 mm

/gate/encapsulatingBox/daughters/name voxel_0267
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0267/geometry/setXLength 0.2 mm
/gate/voxel_0267/geometry/setYLength 1 mm
/gate/voxel_0267/geometry/setZLength 2.2 mm
/gate/voxel_0267/setMaterial Plastic
/gate/voxel_0267/vis/forceSolid
/gate/voxel_0267/vis/setColor yellow
/gate/voxel_0267/placement/setTranslation 1.1 0 13.1 mm

/gate/encapsulatingBox/daughters/name voxel_0268
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0268/geometry/setXLength 0.2 mm
/gate/voxel_0268/geometry/setYLength 1 mm
/gate/voxel_0268/geometry/setZLength 1.2 mm
/gate/voxel_0268/setMaterial Plastic
/gate/voxel_0268/vis/forceSolid
/gate/voxel_0268/vis/setColor yellow
/gate/voxel_0268/placement/setTranslation 1.1 0 17.6 mm

/gate/encapsulatingBox/daughters/name voxel_0269
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0269/geometry/setXLength 0.2 mm
/gate/voxel_0269/geometry/setYLength 1 mm
/gate/voxel_0269/geometry/setZLength 4.2 mm
/gate/voxel_0269/setMaterial Plastic
/gate/voxel_0269/vis/forceSolid
/gate/voxel_0269/vis/setColor yellow
/gate/voxel_0269/placement/setTranslation 1.3 0 -20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0270
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0270/geometry/setXLength 0.2 mm
/gate/voxel_0270/geometry/setYLength 1 mm
/gate/voxel_0270/geometry/setZLength 2.0 mm
/gate/voxel_0270/setMaterial Plastic
/gate/voxel_0270/vis/forceSolid
/gate/voxel_0270/vis/setColor yellow
/gate/voxel_0270/placement/setTranslation 1.3 0 13.4 mm

/gate/encapsulatingBox/daughters/name voxel_0271
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0271/geometry/setXLength 0.2 mm
/gate/voxel_0271/geometry/setYLength 1 mm
/gate/voxel_0271/geometry/setZLength 1.2 mm
/gate/voxel_0271/setMaterial Plastic
/gate/voxel_0271/vis/forceSolid
/gate/voxel_0271/vis/setColor yellow
/gate/voxel_0271/placement/setTranslation 1.3 0 17.8 mm

/gate/encapsulatingBox/daughters/name voxel_0272
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0272/geometry/setXLength 0.2 mm
/gate/voxel_0272/geometry/setYLength 1 mm
/gate/voxel_0272/geometry/setZLength 3.8 mm
/gate/voxel_0272/setMaterial Plastic
/gate/voxel_0272/vis/forceSolid
/gate/voxel_0272/vis/setColor yellow
/gate/voxel_0272/placement/setTranslation 1.5 0 -20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0273
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0273/geometry/setXLength 0.2 mm
/gate/voxel_0273/geometry/setYLength 1 mm
/gate/voxel_0273/geometry/setZLength 2.0 mm
/gate/voxel_0273/setMaterial Plastic
/gate/voxel_0273/vis/forceSolid
/gate/voxel_0273/vis/setColor yellow
/gate/voxel_0273/placement/setTranslation 1.5 0 13.6 mm

/gate/encapsulatingBox/daughters/name voxel_0274
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0274/geometry/setXLength 0.2 mm
/gate/voxel_0274/geometry/setYLength 1 mm
/gate/voxel_0274/geometry/setZLength 1.0 mm
/gate/voxel_0274/setMaterial Plastic
/gate/voxel_0274/vis/forceSolid
/gate/voxel_0274/vis/setColor yellow
/gate/voxel_0274/placement/setTranslation 1.5 0 17.9 mm

/gate/encapsulatingBox/daughters/name voxel_0275
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0275/geometry/setXLength 0.2 mm
/gate/voxel_0275/geometry/setYLength 1 mm
/gate/voxel_0275/geometry/setZLength 3.4 mm
/gate/voxel_0275/setMaterial Plastic
/gate/voxel_0275/vis/forceSolid
/gate/voxel_0275/vis/setColor yellow
/gate/voxel_0275/placement/setTranslation 1.7 0 -20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0276
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0276/geometry/setXLength 0.2 mm
/gate/voxel_0276/geometry/setYLength 1 mm
/gate/voxel_0276/geometry/setZLength 2.0 mm
/gate/voxel_0276/setMaterial Plastic
/gate/voxel_0276/vis/forceSolid
/gate/voxel_0276/vis/setColor yellow
/gate/voxel_0276/placement/setTranslation 1.7 0 14.0 mm

/gate/encapsulatingBox/daughters/name voxel_0277
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0277/geometry/setXLength 0.2 mm
/gate/voxel_0277/geometry/setYLength 1 mm
/gate/voxel_0277/geometry/setZLength 1.0 mm
/gate/voxel_0277/setMaterial Plastic
/gate/voxel_0277/vis/forceSolid
/gate/voxel_0277/vis/setColor yellow
/gate/voxel_0277/placement/setTranslation 1.7 0 18.1 mm

/gate/encapsulatingBox/daughters/name voxel_0278
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0278/geometry/setXLength 0.2 mm
/gate/voxel_0278/geometry/setYLength 1 mm
/gate/voxel_0278/geometry/setZLength 2.8 mm
/gate/voxel_0278/setMaterial Plastic
/gate/voxel_0278/vis/forceSolid
/gate/voxel_0278/vis/setColor yellow
/gate/voxel_0278/placement/setTranslation 1.9 0 -21.0 mm

/gate/encapsulatingBox/daughters/name voxel_0279
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0279/geometry/setXLength 0.2 mm
/gate/voxel_0279/geometry/setYLength 1 mm
/gate/voxel_0279/geometry/setZLength 2.2 mm
/gate/voxel_0279/setMaterial Plastic
/gate/voxel_0279/vis/forceSolid
/gate/voxel_0279/vis/setColor yellow
/gate/voxel_0279/placement/setTranslation 1.9 0 14.3 mm

/gate/encapsulatingBox/daughters/name voxel_0280
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0280/geometry/setXLength 0.2 mm
/gate/voxel_0280/geometry/setYLength 1 mm
/gate/voxel_0280/geometry/setZLength 1.2 mm
/gate/voxel_0280/setMaterial Plastic
/gate/voxel_0280/vis/forceSolid
/gate/voxel_0280/vis/setColor yellow
/gate/voxel_0280/placement/setTranslation 1.9 0 18.2 mm

/gate/encapsulatingBox/daughters/name voxel_0281
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0281/geometry/setXLength 0.2 mm
/gate/voxel_0281/geometry/setYLength 1 mm
/gate/voxel_0281/geometry/setZLength 2.4 mm
/gate/voxel_0281/setMaterial Plastic
/gate/voxel_0281/vis/forceSolid
/gate/voxel_0281/vis/setColor yellow
/gate/voxel_0281/placement/setTranslation 2.1 0 -21.0 mm

/gate/encapsulatingBox/daughters/name voxel_0282
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0282/geometry/setXLength 0.2 mm
/gate/voxel_0282/geometry/setYLength 1 mm
/gate/voxel_0282/geometry/setZLength 2.0 mm
/gate/voxel_0282/setMaterial Plastic
/gate/voxel_0282/vis/forceSolid
/gate/voxel_0282/vis/setColor yellow
/gate/voxel_0282/placement/setTranslation 2.1 0 14.6 mm

/gate/encapsulatingBox/daughters/name voxel_0283
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0283/geometry/setXLength 0.2 mm
/gate/voxel_0283/geometry/setYLength 1 mm
/gate/voxel_0283/geometry/setZLength 1.2 mm
/gate/voxel_0283/setMaterial Plastic
/gate/voxel_0283/vis/forceSolid
/gate/voxel_0283/vis/setColor yellow
/gate/voxel_0283/placement/setTranslation 2.1 0 18.4 mm

/gate/encapsulatingBox/daughters/name voxel_0284
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0284/geometry/setXLength 0.2 mm
/gate/voxel_0284/geometry/setYLength 1 mm
/gate/voxel_0284/geometry/setZLength 1.6 mm
/gate/voxel_0284/setMaterial Plastic
/gate/voxel_0284/vis/forceSolid
/gate/voxel_0284/vis/setColor yellow
/gate/voxel_0284/placement/setTranslation 2.3 0 -21.0 mm

/gate/encapsulatingBox/daughters/name voxel_0285
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0285/geometry/setXLength 0.2 mm
/gate/voxel_0285/geometry/setYLength 1 mm
/gate/voxel_0285/geometry/setZLength 2.0 mm
/gate/voxel_0285/setMaterial Plastic
/gate/voxel_0285/vis/forceSolid
/gate/voxel_0285/vis/setColor yellow
/gate/voxel_0285/placement/setTranslation 2.3 0 14.8 mm

/gate/encapsulatingBox/daughters/name voxel_0286
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0286/geometry/setXLength 0.2 mm
/gate/voxel_0286/geometry/setYLength 1 mm
/gate/voxel_0286/geometry/setZLength 1.2 mm
/gate/voxel_0286/setMaterial Plastic
/gate/voxel_0286/vis/forceSolid
/gate/voxel_0286/vis/setColor yellow
/gate/voxel_0286/placement/setTranslation 2.3 0 18.6 mm

/gate/encapsulatingBox/daughters/name voxel_0287
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0287/geometry/setXLength 0.2 mm
/gate/voxel_0287/geometry/setYLength 1 mm
/gate/voxel_0287/geometry/setZLength 1.0 mm
/gate/voxel_0287/setMaterial Plastic
/gate/voxel_0287/vis/forceSolid
/gate/voxel_0287/vis/setColor yellow
/gate/voxel_0287/placement/setTranslation 2.5 0 -21.1 mm

/gate/encapsulatingBox/daughters/name voxel_0288
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0288/geometry/setXLength 0.2 mm
/gate/voxel_0288/geometry/setYLength 1 mm
/gate/voxel_0288/geometry/setZLength 1.8 mm
/gate/voxel_0288/setMaterial Plastic
/gate/voxel_0288/vis/forceSolid
/gate/voxel_0288/vis/setColor yellow
/gate/voxel_0288/placement/setTranslation 2.5 0 14.9 mm

/gate/encapsulatingBox/daughters/name voxel_0289
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0289/geometry/setXLength 0.2 mm
/gate/voxel_0289/geometry/setYLength 1 mm
/gate/voxel_0289/geometry/setZLength 1.2 mm
/gate/voxel_0289/setMaterial Plastic
/gate/voxel_0289/vis/forceSolid
/gate/voxel_0289/vis/setColor yellow
/gate/voxel_0289/placement/setTranslation 2.5 0 18.8 mm

/gate/encapsulatingBox/daughters/name voxel_0290
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0290/geometry/setXLength 0.2 mm
/gate/voxel_0290/geometry/setYLength 1 mm
/gate/voxel_0290/geometry/setZLength 2.0 mm
/gate/voxel_0290/setMaterial Plastic
/gate/voxel_0290/vis/forceSolid
/gate/voxel_0290/vis/setColor yellow
/gate/voxel_0290/placement/setTranslation 2.7 0 15.2 mm

/gate/encapsulatingBox/daughters/name voxel_0291
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0291/geometry/setXLength 0.2 mm
/gate/voxel_0291/geometry/setYLength 1 mm
/gate/voxel_0291/geometry/setZLength 1.0 mm
/gate/voxel_0291/setMaterial Plastic
/gate/voxel_0291/vis/forceSolid
/gate/voxel_0291/vis/setColor yellow
/gate/voxel_0291/placement/setTranslation 2.7 0 18.9 mm

/gate/encapsulatingBox/daughters/name voxel_0292
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0292/geometry/setXLength 0.2 mm
/gate/voxel_0292/geometry/setYLength 1 mm
/gate/voxel_0292/geometry/setZLength 2.0 mm
/gate/voxel_0292/setMaterial Plastic
/gate/voxel_0292/vis/forceSolid
/gate/voxel_0292/vis/setColor yellow
/gate/voxel_0292/placement/setTranslation 2.9 0 15.4 mm

/gate/encapsulatingBox/daughters/name voxel_0293
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0293/geometry/setXLength 0.2 mm
/gate/voxel_0293/geometry/setYLength 1 mm
/gate/voxel_0293/geometry/setZLength 1.0 mm
/gate/voxel_0293/setMaterial Plastic
/gate/voxel_0293/vis/forceSolid
/gate/voxel_0293/vis/setColor yellow
/gate/voxel_0293/placement/setTranslation 2.9 0 19.1 mm

/gate/encapsulatingBox/daughters/name voxel_0294
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0294/geometry/setXLength 0.2 mm
/gate/voxel_0294/geometry/setYLength 1 mm
/gate/voxel_0294/geometry/setZLength 2.0 mm
/gate/voxel_0294/setMaterial Plastic
/gate/voxel_0294/vis/forceSolid
/gate/voxel_0294/vis/setColor yellow
/gate/voxel_0294/placement/setTranslation 3.1 0 15.6 mm

/gate/encapsulatingBox/daughters/name voxel_0295
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0295/geometry/setXLength 0.2 mm
/gate/voxel_0295/geometry/setYLength 1 mm
/gate/voxel_0295/geometry/setZLength 1.0 mm
/gate/voxel_0295/setMaterial Plastic
/gate/voxel_0295/vis/forceSolid
/gate/voxel_0295/vis/setColor yellow
/gate/voxel_0295/placement/setTranslation 3.1 0 19.3 mm

/gate/encapsulatingBox/daughters/name voxel_0296
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0296/geometry/setXLength 0.2 mm
/gate/voxel_0296/geometry/setYLength 1 mm
/gate/voxel_0296/geometry/setZLength 1.8 mm
/gate/voxel_0296/setMaterial Plastic
/gate/voxel_0296/vis/forceSolid
/gate/voxel_0296/vis/setColor yellow
/gate/voxel_0296/placement/setTranslation 3.3 0 15.9 mm

/gate/encapsulatingBox/daughters/name voxel_0297
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0297/geometry/setXLength 0.2 mm
/gate/voxel_0297/geometry/setYLength 1 mm
/gate/voxel_0297/geometry/setZLength 1.2 mm
/gate/voxel_0297/setMaterial Plastic
/gate/voxel_0297/vis/forceSolid
/gate/voxel_0297/vis/setColor yellow
/gate/voxel_0297/placement/setTranslation 3.3 0 19.4 mm

/gate/encapsulatingBox/daughters/name voxel_0298
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0298/geometry/setXLength 0.2 mm
/gate/voxel_0298/geometry/setYLength 1 mm
/gate/voxel_0298/geometry/setZLength 1.8 mm
/gate/voxel_0298/setMaterial Plastic
/gate/voxel_0298/vis/forceSolid
/gate/voxel_0298/vis/setColor yellow
/gate/voxel_0298/placement/setTranslation 3.5 0 16.1 mm

/gate/encapsulatingBox/daughters/name voxel_0299
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0299/geometry/setXLength 0.2 mm
/gate/voxel_0299/geometry/setYLength 1 mm
/gate/voxel_0299/geometry/setZLength 1.2 mm
/gate/voxel_0299/setMaterial Plastic
/gate/voxel_0299/vis/forceSolid
/gate/voxel_0299/vis/setColor yellow
/gate/voxel_0299/placement/setTranslation 3.5 0 19.6 mm

/gate/encapsulatingBox/daughters/name voxel_0300
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0300/geometry/setXLength 0.2 mm
/gate/voxel_0300/geometry/setYLength 1 mm
/gate/voxel_0300/geometry/setZLength 1.8 mm
/gate/voxel_0300/setMaterial Plastic
/gate/voxel_0300/vis/forceSolid
/gate/voxel_0300/vis/setColor yellow
/gate/voxel_0300/placement/setTranslation 3.7 0 16.3 mm

/gate/encapsulatingBox/daughters/name voxel_0301
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0301/geometry/setXLength 0.2 mm
/gate/voxel_0301/geometry/setYLength 1 mm
/gate/voxel_0301/geometry/setZLength 1.2 mm
/gate/voxel_0301/setMaterial Plastic
/gate/voxel_0301/vis/forceSolid
/gate/voxel_0301/vis/setColor yellow
/gate/voxel_0301/placement/setTranslation 3.7 0 19.8 mm

/gate/encapsulatingBox/daughters/name voxel_0302
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0302/geometry/setXLength 0.2 mm
/gate/voxel_0302/geometry/setYLength 1 mm
/gate/voxel_0302/geometry/setZLength 1.2 mm
/gate/voxel_0302/setMaterial Plastic
/gate/voxel_0302/vis/forceSolid
/gate/voxel_0302/vis/setColor yellow
/gate/voxel_0302/placement/setTranslation 3.9 0 16.4 mm

/gate/encapsulatingBox/daughters/name voxel_0303
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0303/geometry/setXLength 0.2 mm
/gate/voxel_0303/geometry/setYLength 1 mm
/gate/voxel_0303/geometry/setZLength 1.0 mm
/gate/voxel_0303/setMaterial Plastic
/gate/voxel_0303/vis/forceSolid
/gate/voxel_0303/vis/setColor yellow
/gate/voxel_0303/placement/setTranslation 3.9 0 19.9 mm

/gate/encapsulatingBox/daughters/name voxel_0304
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0304/geometry/setXLength 0.2 mm
/gate/voxel_0304/geometry/setYLength 1 mm
/gate/voxel_0304/geometry/setZLength 0.8 mm
/gate/voxel_0304/setMaterial Plastic
/gate/voxel_0304/vis/forceSolid
/gate/voxel_0304/vis/setColor yellow
/gate/voxel_0304/placement/setTranslation 4.1 0 16.4 mm

/gate/encapsulatingBox/daughters/name voxel_0305
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0305/geometry/setXLength 0.2 mm
/gate/voxel_0305/geometry/setYLength 1 mm
/gate/voxel_0305/geometry/setZLength 1.0 mm
/gate/voxel_0305/setMaterial Plastic
/gate/voxel_0305/vis/forceSolid
/gate/voxel_0305/vis/setColor yellow
/gate/voxel_0305/placement/setTranslation 4.1 0 20.1 mm

/gate/encapsulatingBox/daughters/name voxel_0306
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0306/geometry/setXLength 0.2 mm
/gate/voxel_0306/geometry/setYLength 1 mm
/gate/voxel_0306/geometry/setZLength 0.4 mm
/gate/voxel_0306/setMaterial Plastic
/gate/voxel_0306/vis/forceSolid
/gate/voxel_0306/vis/setColor yellow
/gate/voxel_0306/placement/setTranslation 4.3 0 16.4 mm

/gate/encapsulatingBox/daughters/name voxel_0307
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0307/geometry/setXLength 0.2 mm
/gate/voxel_0307/geometry/setYLength 1 mm
/gate/voxel_0307/geometry/setZLength 0.6 mm
/gate/voxel_0307/setMaterial Plastic
/gate/voxel_0307/vis/forceSolid
/gate/voxel_0307/vis/setColor yellow
/gate/voxel_0307/placement/setTranslation 4.3 0 17.5 mm

/gate/encapsulatingBox/daughters/name voxel_0308
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0308/geometry/setXLength 0.2 mm
/gate/voxel_0308/geometry/setYLength 1 mm
/gate/voxel_0308/geometry/setZLength 1.0 mm
/gate/voxel_0308/setMaterial Plastic
/gate/voxel_0308/vis/forceSolid
/gate/voxel_0308/vis/setColor yellow
/gate/voxel_0308/placement/setTranslation 4.3 0 20.3 mm

/gate/encapsulatingBox/daughters/name voxel_0309
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0309/geometry/setXLength 0.2 mm
/gate/voxel_0309/geometry/setYLength 1 mm
/gate/voxel_0309/geometry/setZLength 1.0 mm
/gate/voxel_0309/setMaterial Plastic
/gate/voxel_0309/vis/forceSolid
/gate/voxel_0309/vis/setColor yellow
/gate/voxel_0309/placement/setTranslation 4.5 0 17.5 mm

/gate/encapsulatingBox/daughters/name voxel_0310
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0310/geometry/setXLength 0.2 mm
/gate/voxel_0310/geometry/setYLength 1 mm
/gate/voxel_0310/geometry/setZLength 1.0 mm
/gate/voxel_0310/setMaterial Plastic
/gate/voxel_0310/vis/forceSolid
/gate/voxel_0310/vis/setColor yellow
/gate/voxel_0310/placement/setTranslation 4.5 0 20.5 mm

/gate/encapsulatingBox/daughters/name voxel_0311
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0311/geometry/setXLength 0.2 mm
/gate/voxel_0311/geometry/setYLength 1 mm
/gate/voxel_0311/geometry/setZLength 1.4 mm
/gate/voxel_0311/setMaterial Plastic
/gate/voxel_0311/vis/forceSolid
/gate/voxel_0311/vis/setColor yellow
/gate/voxel_0311/placement/setTranslation 4.7 0 17.7 mm

/gate/encapsulatingBox/daughters/name voxel_0312
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0312/geometry/setXLength 0.4 mm
/gate/voxel_0312/geometry/setYLength 1 mm
/gate/voxel_0312/geometry/setZLength 1.0 mm
/gate/voxel_0312/setMaterial Plastic
/gate/voxel_0312/vis/forceSolid
/gate/voxel_0312/vis/setColor yellow
/gate/voxel_0312/placement/setTranslation 4.8 0 20.7 mm

/gate/encapsulatingBox/daughters/name voxel_0313
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0313/geometry/setXLength 0.2 mm
/gate/voxel_0313/geometry/setYLength 1 mm
/gate/voxel_0313/geometry/setZLength 1.6 mm
/gate/voxel_0313/setMaterial Plastic
/gate/voxel_0313/vis/forceSolid
/gate/voxel_0313/vis/setColor yellow
/gate/voxel_0313/placement/setTranslation 4.9 0 17.8 mm

/gate/encapsulatingBox/daughters/name voxel_0314
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0314/geometry/setXLength 0.2 mm
/gate/voxel_0314/geometry/setYLength 1 mm
/gate/voxel_0314/geometry/setZLength 1.8 mm
/gate/voxel_0314/setMaterial Plastic
/gate/voxel_0314/vis/forceSolid
/gate/voxel_0314/vis/setColor yellow
/gate/voxel_0314/placement/setTranslation 5.1 0 17.9 mm

/gate/encapsulatingBox/daughters/name voxel_0315
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0315/geometry/setXLength 0.2 mm
/gate/voxel_0315/geometry/setYLength 1 mm
/gate/voxel_0315/geometry/setZLength 1.0 mm
/gate/voxel_0315/setMaterial Plastic
/gate/voxel_0315/vis/forceSolid
/gate/voxel_0315/vis/setColor yellow
/gate/voxel_0315/placement/setTranslation 5.1 0 20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0316
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0316/geometry/setXLength 0.2 mm
/gate/voxel_0316/geometry/setYLength 1 mm
/gate/voxel_0316/geometry/setZLength 1.8 mm
/gate/voxel_0316/setMaterial Plastic
/gate/voxel_0316/vis/forceSolid
/gate/voxel_0316/vis/setColor yellow
/gate/voxel_0316/placement/setTranslation 5.3 0 18.1 mm

/gate/encapsulatingBox/daughters/name voxel_0317
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0317/geometry/setXLength 0.2 mm
/gate/voxel_0317/geometry/setYLength 1 mm
/gate/voxel_0317/geometry/setZLength 1.2 mm
/gate/voxel_0317/setMaterial Plastic
/gate/voxel_0317/vis/forceSolid
/gate/voxel_0317/vis/setColor yellow
/gate/voxel_0317/placement/setTranslation 5.3 0 21.0 mm

/gate/encapsulatingBox/daughters/name voxel_0318
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0318/geometry/setXLength 0.2 mm
/gate/voxel_0318/geometry/setYLength 1 mm
/gate/voxel_0318/geometry/setZLength 1.8 mm
/gate/voxel_0318/setMaterial Plastic
/gate/voxel_0318/vis/forceSolid
/gate/voxel_0318/vis/setColor yellow
/gate/voxel_0318/placement/setTranslation 5.5 0 18.3 mm

/gate/encapsulatingBox/daughters/name voxel_0319
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0319/geometry/setXLength 0.2 mm
/gate/voxel_0319/geometry/setYLength 1 mm
/gate/voxel_0319/geometry/setZLength 1.4 mm
/gate/voxel_0319/setMaterial Plastic
/gate/voxel_0319/vis/forceSolid
/gate/voxel_0319/vis/setColor yellow
/gate/voxel_0319/placement/setTranslation 5.5 0 21.1 mm

/gate/encapsulatingBox/daughters/name voxel_0320
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0320/geometry/setXLength 0.2 mm
/gate/voxel_0320/geometry/setYLength 1 mm
/gate/voxel_0320/geometry/setZLength 1.6 mm
/gate/voxel_0320/setMaterial Plastic
/gate/voxel_0320/vis/forceSolid
/gate/voxel_0320/vis/setColor yellow
/gate/voxel_0320/placement/setTranslation 5.7 0 18.6 mm

/gate/encapsulatingBox/daughters/name voxel_0321
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0321/geometry/setXLength 0.4 mm
/gate/voxel_0321/geometry/setYLength 1 mm
/gate/voxel_0321/geometry/setZLength 1.6 mm
/gate/voxel_0321/setMaterial Plastic
/gate/voxel_0321/vis/forceSolid
/gate/voxel_0321/vis/setColor yellow
/gate/voxel_0321/placement/setTranslation 5.8 0 21.2 mm

/gate/encapsulatingBox/daughters/name voxel_0322
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0322/geometry/setXLength 0.2 mm
/gate/voxel_0322/geometry/setYLength 1 mm
/gate/voxel_0322/geometry/setZLength 1.6 mm
/gate/voxel_0322/setMaterial Plastic
/gate/voxel_0322/vis/forceSolid
/gate/voxel_0322/vis/setColor yellow
/gate/voxel_0322/placement/setTranslation 5.9 0 18.8 mm

/gate/encapsulatingBox/daughters/name voxel_0323
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0323/geometry/setXLength 0.2 mm
/gate/voxel_0323/geometry/setYLength 1 mm
/gate/voxel_0323/geometry/setZLength 4.0 mm
/gate/voxel_0323/setMaterial Plastic
/gate/voxel_0323/vis/forceSolid
/gate/voxel_0323/vis/setColor yellow
/gate/voxel_0323/placement/setTranslation 6.1 0 20.2 mm

/gate/encapsulatingBox/daughters/name voxel_0324
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0324/geometry/setXLength 0.2 mm
/gate/voxel_0324/geometry/setYLength 1 mm
/gate/voxel_0324/geometry/setZLength 3.6 mm
/gate/voxel_0324/setMaterial Plastic
/gate/voxel_0324/vis/forceSolid
/gate/voxel_0324/vis/setColor yellow
/gate/voxel_0324/placement/setTranslation 6.3 0 20.4 mm

/gate/encapsulatingBox/daughters/name voxel_0325
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0325/geometry/setXLength 0.2 mm
/gate/voxel_0325/geometry/setYLength 1 mm
/gate/voxel_0325/geometry/setZLength 3.6 mm
/gate/voxel_0325/setMaterial Plastic
/gate/voxel_0325/vis/forceSolid
/gate/voxel_0325/vis/setColor yellow
/gate/voxel_0325/placement/setTranslation 6.5 0 20.6 mm

/gate/encapsulatingBox/daughters/name voxel_0326
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0326/geometry/setXLength 0.2 mm
/gate/voxel_0326/geometry/setYLength 1 mm
/gate/voxel_0326/geometry/setZLength 3.4 mm
/gate/voxel_0326/setMaterial Plastic
/gate/voxel_0326/vis/forceSolid
/gate/voxel_0326/vis/setColor yellow
/gate/voxel_0326/placement/setTranslation 6.7 0 20.7 mm

/gate/encapsulatingBox/daughters/name voxel_0327
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0327/geometry/setXLength 0.2 mm
/gate/voxel_0327/geometry/setYLength 1 mm
/gate/voxel_0327/geometry/setZLength 3.4 mm
/gate/voxel_0327/setMaterial Plastic
/gate/voxel_0327/vis/forceSolid
/gate/voxel_0327/vis/setColor yellow
/gate/voxel_0327/placement/setTranslation 6.9 0 20.9 mm

/gate/encapsulatingBox/daughters/name voxel_0328
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0328/geometry/setXLength 0.2 mm
/gate/voxel_0328/geometry/setYLength 1 mm
/gate/voxel_0328/geometry/setZLength 3.4 mm
/gate/voxel_0328/setMaterial Plastic
/gate/voxel_0328/vis/forceSolid
/gate/voxel_0328/vis/setColor yellow
/gate/voxel_0328/placement/setTranslation 7.1 0 21.1 mm

/gate/encapsulatingBox/daughters/name voxel_0329
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0329/geometry/setXLength 0.2 mm
/gate/voxel_0329/geometry/setYLength 1 mm
/gate/voxel_0329/geometry/setZLength 3.4 mm
/gate/voxel_0329/setMaterial Plastic
/gate/voxel_0329/vis/forceSolid
/gate/voxel_0329/vis/setColor yellow
/gate/voxel_0329/placement/setTranslation 7.3 0 21.3 mm

/gate/encapsulatingBox/daughters/name voxel_0330
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0330/geometry/setXLength 0.2 mm
/gate/voxel_0330/geometry/setYLength 1 mm
/gate/voxel_0330/geometry/setZLength 3.4 mm
/gate/voxel_0330/setMaterial Plastic
/gate/voxel_0330/vis/forceSolid
/gate/voxel_0330/vis/setColor yellow
/gate/voxel_0330/placement/setTranslation 7.5 0 21.5 mm

/gate/encapsulatingBox/daughters/name voxel_0331
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0331/geometry/setXLength 0.2 mm
/gate/voxel_0331/geometry/setYLength 1 mm
/gate/voxel_0331/geometry/setZLength 3.2 mm
/gate/voxel_0331/setMaterial Plastic
/gate/voxel_0331/vis/forceSolid
/gate/voxel_0331/vis/setColor yellow
/gate/voxel_0331/placement/setTranslation 7.7 0 21.6 mm

/gate/encapsulatingBox/daughters/name voxel_0332
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0332/geometry/setXLength 0.2 mm
/gate/voxel_0332/geometry/setYLength 1 mm
/gate/voxel_0332/geometry/setZLength 2.6 mm
/gate/voxel_0332/setMaterial Plastic
/gate/voxel_0332/vis/forceSolid
/gate/voxel_0332/vis/setColor yellow
/gate/voxel_0332/placement/setTranslation 7.9 0 21.7 mm

/gate/encapsulatingBox/daughters/name voxel_0333
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0333/geometry/setXLength 0.2 mm
/gate/voxel_0333/geometry/setYLength 1 mm
/gate/voxel_0333/geometry/setZLength 2.4 mm
/gate/voxel_0333/setMaterial Plastic
/gate/voxel_0333/vis/forceSolid
/gate/voxel_0333/vis/setColor yellow
/gate/voxel_0333/placement/setTranslation 8.1 0 21.8 mm

/gate/encapsulatingBox/daughters/name voxel_0334
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0334/geometry/setXLength 0.2 mm
/gate/voxel_0334/geometry/setYLength 1 mm
/gate/voxel_0334/geometry/setZLength 2.0 mm
/gate/voxel_0334/setMaterial Plastic
/gate/voxel_0334/vis/forceSolid
/gate/voxel_0334/vis/setColor yellow
/gate/voxel_0334/placement/setTranslation 8.3 0 21.8 mm

/gate/encapsulatingBox/daughters/name voxel_0335
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0335/geometry/setXLength 0.2 mm
/gate/voxel_0335/geometry/setYLength 1 mm
/gate/voxel_0335/geometry/setZLength 1.6 mm
/gate/voxel_0335/setMaterial Plastic
/gate/voxel_0335/vis/forceSolid
/gate/voxel_0335/vis/setColor yellow
/gate/voxel_0335/placement/setTranslation 8.5 0 21.8 mm

/gate/encapsulatingBox/daughters/name voxel_0336
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0336/geometry/setXLength 0.2 mm
/gate/voxel_0336/geometry/setYLength 1 mm
/gate/voxel_0336/geometry/setZLength 1.2 mm
/gate/voxel_0336/setMaterial Plastic
/gate/voxel_0336/vis/forceSolid
/gate/voxel_0336/vis/setColor yellow
/gate/voxel_0336/placement/setTranslation 8.7 0 21.8 mm

/gate/encapsulatingBox/daughters/name voxel_0337
/gate/encapsulatingBox/daughters/insert box
/gate/voxel_0337/geometry/setXLength 0.2 mm
/gate/voxel_0337/geometry/setYLength 1 mm
/gate/voxel_0337/geometry/setZLength 0.4 mm
/gate/voxel_0337/setMaterial Plastic
/gate/voxel_0337/vis/forceSolid
/gate/voxel_0337/vis/setColor yellow
/gate/voxel_0337/placement/setTranslation 8.9 0 21.8 mm

